DROP TABLE ESB.AUDITSTATE;
CREATE TABLE ESB.AUDITSTATE  ( 
	ID   	VARCHAR(25) NOT NULL,
	STATE	VARCHAR(40) NOT NULL 
	)
;
COMMENT ON TABLE ESB.AUDITSTATE IS 'ÉóºË×´Ì¬±í'
;
COMMENT ON COLUMN ESB.AUDITSTATE.ID IS 'IDÖ÷¼ü'
;
COMMENT ON COLUMN ESB.AUDITSTATE.STATE IS 'ÉóºË×´Ì¬'
;
INSERT INTO ESB.AUDITSTATE(ID, STATE)
  VALUES('0', 'ÐÂÔö')
;
INSERT INTO ESB.AUDITSTATE(ID, STATE)
  VALUES('1', '´ýÉóºË')
;
INSERT INTO ESB.AUDITSTATE(ID, STATE)
  VALUES('2', 'Í¨¹ý')
;
INSERT INTO ESB.AUDITSTATE(ID, STATE)
  VALUES('3', '¾Ü¾ø')
;
COMMIT;
COMMIT;
