DROP TABLE ESB.SG_FUNCTION;
CREATE TABLE ESB.SG_FUNCTION  ( 
	FUNCTION_ID       	INTEGER NOT NULL,
	FUNCTION_NAME     	VARCHAR(255) NOT NULL,
	FUNCTION_URL      	VARCHAR(255) NOT NULL,
	FUNCTION_PARENT_ID	VARCHAR(255) NOT NULL,
	FUNCTION_REMARK   	VARCHAR(255) 
	)
;
COMMENT ON TABLE ESB.SG_FUNCTION IS '菜单基本信息表'
;
COMMENT ON COLUMN ESB.SG_FUNCTION.FUNCTION_ID IS '主键ID'
;
COMMENT ON COLUMN ESB.SG_FUNCTION.FUNCTION_NAME IS '菜单名称'
;
COMMENT ON COLUMN ESB.SG_FUNCTION.FUNCTION_URL IS 'URL地址'
;
COMMENT ON COLUMN ESB.SG_FUNCTION.FUNCTION_PARENT_ID IS '父ID'
;
COMMENT ON COLUMN ESB.SG_FUNCTION.FUNCTION_REMARK IS '描述'
;
INSERT INTO ESB.SG_FUNCTION(FUNCTION_ID, FUNCTION_NAME, FUNCTION_URL, FUNCTION_PARENT_ID, FUNCTION_REMARK)
  VALUES(1, '服务管理', '#', '0', '一级菜单服务管理')
;
INSERT INTO ESB.SG_FUNCTION(FUNCTION_ID, FUNCTION_NAME, FUNCTION_URL, FUNCTION_PARENT_ID, FUNCTION_REMARK)
  VALUES(2, '资源管理', '#', '0', '一级菜单资源管理')
;
INSERT INTO ESB.SG_FUNCTION(FUNCTION_ID, FUNCTION_NAME, FUNCTION_URL, FUNCTION_PARENT_ID, FUNCTION_REMARK)
  VALUES(3, '视图查询', '#', '0', '一级菜单视图查询')
;
INSERT INTO ESB.SG_FUNCTION(FUNCTION_ID, FUNCTION_NAME, FUNCTION_URL, FUNCTION_PARENT_ID, FUNCTION_REMARK)
  VALUES(4, '系统管理', '#', '0', '一级菜单系统管理')
;
INSERT INTO ESB.SG_FUNCTION(FUNCTION_ID, FUNCTION_NAME, FUNCTION_URL, FUNCTION_PARENT_ID, FUNCTION_REMARK)
  VALUES(5, '操作管理', '/jsp/operationManager.jsp', '1', '二级菜单操作管理')
;
INSERT INTO ESB.SG_FUNCTION(FUNCTION_ID, FUNCTION_NAME, FUNCTION_URL, FUNCTION_PARENT_ID, FUNCTION_REMARK)
  VALUES(6, '服务管理', '/jsp/serviceInfoManager.jsp', '1', '二级菜单服务管理')
;
INSERT INTO ESB.SG_FUNCTION(FUNCTION_ID, FUNCTION_NAME, FUNCTION_URL, FUNCTION_PARENT_ID, FUNCTION_REMARK)
  VALUES(7, '接口管理', '/html/interfaceManagement.html', '1', '二级菜单接口管理')
;
INSERT INTO ESB.SG_FUNCTION(FUNCTION_ID, FUNCTION_NAME, FUNCTION_URL, FUNCTION_PARENT_ID, FUNCTION_REMARK)
  VALUES(8, '服务审核', '/jsp/audit.jsp', '1', '二级菜单服务审核')
;
INSERT INTO ESB.SG_FUNCTION(FUNCTION_ID, FUNCTION_NAME, FUNCTION_URL, FUNCTION_PARENT_ID, FUNCTION_REMARK)
  VALUES(9, '服务分类管理', '/jsp/serviceCategoryManager.jsp', '1', '二级菜单服务分类管理')
;
INSERT INTO ESB.SG_FUNCTION(FUNCTION_ID, FUNCTION_NAME, FUNCTION_URL, FUNCTION_PARENT_ID, FUNCTION_REMARK)
  VALUES(10, '元数据管理', '/jsp/metadataManager.jsp', '1', '二级菜单元数据管理')
;
INSERT INTO ESB.SG_FUNCTION(FUNCTION_ID, FUNCTION_NAME, FUNCTION_URL, FUNCTION_PARENT_ID, FUNCTION_REMARK)
  VALUES(11, '元数据结构管理', '/jsp/metadataStructsManager.jsp', '1', '二级菜单元数据结构管理')
;
INSERT INTO ESB.SG_FUNCTION(FUNCTION_ID, FUNCTION_NAME, FUNCTION_URL, FUNCTION_PARENT_ID, FUNCTION_REMARK)
  VALUES(12, '接入系统管理', '/jsp/systemInfoManager.jsp', '1', '二级菜单接入系统管理')
;
INSERT INTO ESB.SG_FUNCTION(FUNCTION_ID, FUNCTION_NAME, FUNCTION_URL, FUNCTION_PARENT_ID, FUNCTION_REMARK)
  VALUES(13, '调用关系管理', '/jsp/invokeManager.jsp', '1', '二级菜单调用关系管理')
;
INSERT INTO ESB.SG_FUNCTION(FUNCTION_ID, FUNCTION_NAME, FUNCTION_URL, FUNCTION_PARENT_ID, FUNCTION_REMARK)
  VALUES(14, '资源导入', '/jsp/resourceImport.jsp', '2', '')
;
INSERT INTO ESB.SG_FUNCTION(FUNCTION_ID, FUNCTION_NAME, FUNCTION_URL, FUNCTION_PARENT_ID, FUNCTION_REMARK)
  VALUES(29, '用户管理', '/jsp/userManager.jsp', '4', '')
;
INSERT INTO ESB.SG_FUNCTION(FUNCTION_ID, FUNCTION_NAME, FUNCTION_URL, FUNCTION_PARENT_ID, FUNCTION_REMARK)
  VALUES(15, '资源导出', '/jsp/resourceExport.jsp', '2', '')
;
INSERT INTO ESB.SG_FUNCTION(FUNCTION_ID, FUNCTION_NAME, FUNCTION_URL, FUNCTION_PARENT_ID, FUNCTION_REMARK)
  VALUES(16, '映射文档导出', '/html/exportExcel.html', '2', '')
;
INSERT INTO ESB.SG_FUNCTION(FUNCTION_ID, FUNCTION_NAME, FUNCTION_URL, FUNCTION_PARENT_ID, FUNCTION_REMARK)
  VALUES(17, '系统级别SQL导出', '/jsp/sysSql.jsp', '2', '')
;
INSERT INTO ESB.SG_FUNCTION(FUNCTION_ID, FUNCTION_NAME, FUNCTION_URL, FUNCTION_PARENT_ID, FUNCTION_REMARK)
  VALUES(18, 'PDF导出', '/jsp/pdf.jsp', '2', '')
;
INSERT INTO ESB.SG_FUNCTION(FUNCTION_ID, FUNCTION_NAME, FUNCTION_URL, FUNCTION_PARENT_ID, FUNCTION_REMARK)
  VALUES(19, '服务调用关系查询', '/jsp/svcAsmRelateView.jsp', '3', '')
;
INSERT INTO ESB.SG_FUNCTION(FUNCTION_ID, FUNCTION_NAME, FUNCTION_URL, FUNCTION_PARENT_ID, FUNCTION_REMARK)
  VALUES(20, '服务详细信息查询', '/jsp/serviceDetailView.jsp', '3', '')
;
INSERT INTO ESB.SG_FUNCTION(FUNCTION_ID, FUNCTION_NAME, FUNCTION_URL, FUNCTION_PARENT_ID, FUNCTION_REMARK)
  VALUES(21, '服务库查询', '/jsp/serviceStore.jsp', '3', '')
;
INSERT INTO ESB.SG_FUNCTION(FUNCTION_ID, FUNCTION_NAME, FUNCTION_URL, FUNCTION_PARENT_ID, FUNCTION_REMARK)
  VALUES(22, '服务统计信息', '/jsp/serviceTotalView.jsp', '3', '')
;
INSERT INTO ESB.SG_FUNCTION(FUNCTION_ID, FUNCTION_NAME, FUNCTION_URL, FUNCTION_PARENT_ID, FUNCTION_REMARK)
  VALUES(23, '服务开发统计信息查询', '/jsp/serviceDevProgressView.jsp', '3', '')
;
INSERT INTO ESB.SG_FUNCTION(FUNCTION_ID, FUNCTION_NAME, FUNCTION_URL, FUNCTION_PARENT_ID, FUNCTION_REMARK)
  VALUES(24, '服务SLA信息查询', '/jsp/sla.jsp', '3', '')
;
INSERT INTO ESB.SG_FUNCTION(FUNCTION_ID, FUNCTION_NAME, FUNCTION_URL, FUNCTION_PARENT_ID, FUNCTION_REMARK)
  VALUES(25, '接入系统服务统计表', '/jsp/sysInvokeServiceView.jsp', '3', '')
;
INSERT INTO ESB.SG_FUNCTION(FUNCTION_ID, FUNCTION_NAME, FUNCTION_URL, FUNCTION_PARENT_ID, FUNCTION_REMARK)
  VALUES(26, '接入系统拓扑图', '/jsp/sysTopology.jsp', '3', '')
;
INSERT INTO ESB.SG_FUNCTION(FUNCTION_ID, FUNCTION_NAME, FUNCTION_URL, FUNCTION_PARENT_ID, FUNCTION_REMARK)
  VALUES(28, '上线统计信息查询', '/jsp/publishTotalView.jsp', '3', '')
;
INSERT INTO ESB.SG_FUNCTION(FUNCTION_ID, FUNCTION_NAME, FUNCTION_URL, FUNCTION_PARENT_ID, FUNCTION_REMARK)
  VALUES(30, '角色管理', '/jsp/roleManager.jsp', '4', '')
;
INSERT INTO ESB.SG_FUNCTION(FUNCTION_ID, FUNCTION_NAME, FUNCTION_URL, FUNCTION_PARENT_ID, FUNCTION_REMARK)
  VALUES(31, '权限管理', '/jsp/functionManager.jsp', '4', '')
;
INSERT INTO ESB.SG_FUNCTION(FUNCTION_ID, FUNCTION_NAME, FUNCTION_URL, FUNCTION_PARENT_ID, FUNCTION_REMARK)
  VALUES(32, '机构管理', '/jsp/orgManager.jsp', '4', '')
;
INSERT INTO ESB.SG_FUNCTION(FUNCTION_ID, FUNCTION_NAME, FUNCTION_URL, FUNCTION_PARENT_ID, FUNCTION_REMARK)
  VALUES(33, '密码修改', '/jsp/passwordManager.jsp', '4', '')
;
INSERT INTO ESB.SG_FUNCTION(FUNCTION_ID, FUNCTION_NAME, FUNCTION_URL, FUNCTION_PARENT_ID, FUNCTION_REMARK)
  VALUES(34, '日志查询', '/html/operationLogQuery.html', '4', '')
;
INSERT INTO ESB.SG_FUNCTION(FUNCTION_ID, FUNCTION_NAME, FUNCTION_URL, FUNCTION_PARENT_ID, FUNCTION_REMARK)
  VALUES(35, '存量交易管理', '#', '0', '')
;
INSERT INTO ESB.SG_FUNCTION(FUNCTION_ID, FUNCTION_NAME, FUNCTION_URL, FUNCTION_PARENT_ID, FUNCTION_REMARK)
  VALUES(36, '存量交易导入', '/jsp/tranimport.jsp', '35', '')
;
INSERT INTO ESB.SG_FUNCTION(FUNCTION_ID, FUNCTION_NAME, FUNCTION_URL, FUNCTION_PARENT_ID, FUNCTION_REMARK)
  VALUES(37, '存量交易管理', '/jsp/tranlink.jsp', '35', '')
;
INSERT INTO ESB.SG_FUNCTION(FUNCTION_ID, FUNCTION_NAME, FUNCTION_URL, FUNCTION_PARENT_ID, FUNCTION_REMARK)
  VALUES(38, '存量交易统计', '/jsp/trancount.jsp', '35', '')
;
COMMIT;
COMMIT;
