DROP TABLE ESB.SG_SYSTEM;
CREATE TABLE ESB.SG_SYSTEM  ( 
	SYS_ID             	VARCHAR(50) NOT NULL,
	SYS_AB             	VARCHAR(100),
	SYS_NAME           	VARCHAR(100),
	REMARK             	VARCHAR(500),
	MODIFYUSER         	VARCHAR(50),
	UPDATETIME         	VARCHAR(50),
	FIRST_PUBLISH_DATE 	VARCHAR(50),
	AVGRESTIME         	VARCHAR(50),
	MAXRESTIME         	VARCHAR(50),
	MAXCONNUM          	INTEGER,
	TIMEOUT            	VARCHAR(50),
	SUCCESSRATE        	VARCHAR(50),
	OUTMAXCONNUM       	INTEGER,
	SECOND_PUBLISH_DATE	VARCHAR(50) 
	)
;
COMMENT ON TABLE ESB.SG_SYSTEM IS '系统基本信息表'
;
COMMENT ON COLUMN ESB.SG_SYSTEM.SYS_ID IS '系统ID'
;
COMMENT ON COLUMN ESB.SG_SYSTEM.SYS_AB IS '系统简称'
;
COMMENT ON COLUMN ESB.SG_SYSTEM.SYS_NAME IS '系统中文名称'
;
COMMENT ON COLUMN ESB.SG_SYSTEM.REMARK IS '系统描述'
;
COMMENT ON COLUMN ESB.SG_SYSTEM.MODIFYUSER IS '更新用户'
;
COMMENT ON COLUMN ESB.SG_SYSTEM.UPDATETIME IS '更新时间'
;
COMMENT ON COLUMN ESB.SG_SYSTEM.FIRST_PUBLISH_DATE IS '系统首次上线日期(提供方)'
;
COMMENT ON COLUMN ESB.SG_SYSTEM.AVGRESTIME IS '承诺平均响应时间'
;
COMMENT ON COLUMN ESB.SG_SYSTEM.MAXRESTIME IS '承诺最大响应时间'
;
COMMENT ON COLUMN ESB.SG_SYSTEM.MAXCONNUM IS '承诺In端最大并发数'
;
COMMENT ON COLUMN ESB.SG_SYSTEM.TIMEOUT IS '超时时间'
;
COMMENT ON COLUMN ESB.SG_SYSTEM.SUCCESSRATE IS '承诺成功率'
;
COMMENT ON COLUMN ESB.SG_SYSTEM.OUTMAXCONNUM IS '承诺Out端最大并发数'
;
COMMENT ON COLUMN ESB.SG_SYSTEM.SECOND_PUBLISH_DATE IS '系统首次上线日期(调用方)'
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0437', 'MMP', '移动营销平台', '', NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, '20140527')
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0370', 'PCRM', '个人银行客户关系管理系统', '', NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, '20131208')
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0211', 'NRPT', '报表及数据分析平台', '', NULL, NULL, '20140819', '60000', NULL, 5, '120000', '90', NULL, '20140819')
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0046', 'ICS', '金融IC卡业务系统', '', NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL)
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0004', 'FHIPP', '分行大前置系统', '', NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, '20140916')
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0329', 'BLXT', '保理系统', '', NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL)
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0327', 'CMP', '现金管理系统', '', NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL)
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0033', 'OSA', '离岸核心系统', '', NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL)
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0213', 'GMP', '金融市场交易管理平台', '', NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL)
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0217', 'OIMS', '机构管理系统', '', NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, '20141022')
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0138', 'BQS', '人行信用报告查询系统', '', NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, '20141022')
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0173', 'EA', '自助报销系统', '', NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL)
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0010', 'GZL', '工作流平台综合业务系统', '', '', '', NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL)
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0023', 'IVR', '客服电话银行系统', '', NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL)
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0307', 'POS', '收单系统', '', NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, '20141201')
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0300', 'FXZZ', '非现金自助渠道服务系统', '', NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, '20141216')
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0034', 'CNAPS', '现代支付系统', '', NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL)
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0076', 'WCBS', '微信银行系统', '', NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, '20141201')
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0317', 'SPMS', '企业年金帐管系统', '0317-企业年金帐管系统', NULL, NULL, '20141201', '15000', NULL, 10, '30000', '90', NULL, NULL)
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0084', 'ESVC', '在线客服系统', '', NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, '20131208')
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0110', 'FRS', '对公债项评级系统', '单笔和批量债项评级计算、基于高级法的风险加权资产计算、经济资本计算、贷款分类、债项评级模型管理', NULL, NULL, '20141201', '5000', NULL, 30, '10000', '90', NULL, '20141022')
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0334', 'TIPS', '国库信息处理系统', '', NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL)
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0059', 'YXNR', '影像内容管理服务平台', '', NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL)
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0313', 'BOND', '储蓄国债系统', '', NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL)
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0357', 'ZHZD', '综合帐单系统', '', NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL)
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0212', 'CMIS', '抵质押品管理系统', '', NULL, NULL, '20141115', '50000', NULL, 20, '100000', '90', NULL, '20141022')
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0369', 'CCRM', '公司及投资银行客户关系管理系统', '', NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL)
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0299', 'cmpay', '中移动手机汇款系统', '', NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL)
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0311', 'JIF', '综合积分管理系统', '', NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL)
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0399', 'WU', '代理西联汇款系统', '', NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL)
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0094', 'FMALL', '网上金融超市', '', NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, '20141201')
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0106', 'NBIA', '互联网金融信息交换平台', '', NULL, NULL, '20141201', '30000', NULL, 60, '60000', '90', NULL, '20141201')
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0112', 'KFGK', '客服终端安全管控系统', '', NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, '20141022')
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0149', 'EBTM', '电子银行交易监控系统', '', NULL, NULL, '20141201', '2500', NULL, 100, '5000', '90', NULL, NULL)
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0215', 'PLBS', '零售信贷服务系统', '', NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, '20141201')
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('default', 'default', '默认机构', '', NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL)
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0001', 'SOP', '核心业务系统', '', NULL, NULL, '20131208', '30000', NULL, 20, '60000', '90', NULL, '20131221')
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0003', 'ZHIPP', '总行大前置系统', '', '', '', '20131208', '27500', NULL, 15, '55000', '90', NULL, '20140916')
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0005', 'COP', '核心前台系统', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0006', 'CPC', '业务集中CPC/SDP系统', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20131208')
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0008', 'UAAS', '统一认证授权平台', '', NULL, NULL, '20131208', '30000', NULL, 10, '60000', '90', NULL, NULL)
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0027', 'PWM', '理财业务销售系统', '', NULL, NULL, '20140218', '30000', NULL, 200, '60000', '90', NULL, '20131221')
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0014', 'nbper', '个人网银系统', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20131208')
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0015', 'nbent', '公司网银系统', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20140628')
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0017', 'mbper', '个人手机银行系统', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20141201')
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0020', 'mdp', '通知平台系统', '', NULL, NULL, '20131208', '25000', NULL, 10, '50000', '90', NULL, NULL)
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0025', 'BPP', '客服业务处理系统', '', NULL, NULL, '20141201', '10000', NULL, 60, '20000', '90', NULL, '20131208')
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0026', 'HJJY', '黄金交易管理系统', NULL, NULL, NULL, '20140527', '17500', NULL, 25, '35000', '90', NULL, NULL)
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0825', 'NBH', '柜面及消息服务系统', '', NULL, NULL, '20140527', '15000', NULL, 30, '30000', '90', NULL, NULL)
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0028', 'WHB', '外汇宝系统', NULL, NULL, NULL, '20140527', '15000', NULL, 100, '30000', '90', NULL, NULL)
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0209', 'UIAS', '统一身份和访问管理系统', '新统一认证系统', NULL, NULL, '20141022', '45000', NULL, 105, '90000', '90', NULL, '20131208')
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0029', 'YJT', '银基通系统', NULL, NULL, NULL, '20140218', '30000', NULL, 50, '60000', '90', NULL, '20131221')
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0030', 'SFCG', '第三方存管系统', NULL, NULL, NULL, '20140527', '150000', NULL, 10, '300000', '90', NULL, '20141216')
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0037', 'BCMS', '信用卡前置系统', NULL, NULL, NULL, '20140527', '30000', NULL, 10, '60000', '90', NULL, NULL)
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0044', 'FES', '新一代网点平台系统', '', NULL, NULL, '20141201', '15000', NULL, 50, '30000', '90', NULL, '20140628')
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0200', 'ESB', '企业服务总线', '', NULL, NULL, '20140916', '45000', NULL, 20, '90000', '90', NULL, '20141022')
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0201', 'ECIF', '企业级客户信息管理系统', NULL, NULL, NULL, '20131221', '2500', NULL, 128, '5000', '90', NULL, '20131208')
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0202', 'BIP', '业务集成平台', NULL, NULL, NULL, '20131208', '30000', NULL, 100, '60000', '90', NULL, '20131208')
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0366', 'ALS6', '风险管理信息系统', NULL, NULL, NULL, '20131208', '29500', NULL, 160, '59000', '90', NULL, '20140527')
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0400', 'XPRIC', '外汇报价引擎系统', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0203', 'GLS', '会计核算及总账系统', '', NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL)
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0337', 'XFUND', '结售汇及报价平盘系统', NULL, NULL, NULL, '20140628', '90000', NULL, 50, '180000', '90', NULL, NULL)
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0214', 'TMS', '企业财资管理平台', '', '', '', NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL)
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0205', 'BPMP', '业务流程管理平台', '', NULL, NULL, '20141022', '50000', NULL, 200, '100000', '90', NULL, '20131208')
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0204', 'MMPP', '代客及代理业务处理平台', '', NULL, NULL, '20140628', '30000', NULL, 250, '60000', '90', NULL, '20131208')
;
INSERT INTO ESB.SG_SYSTEM(SYS_ID, SYS_AB, SYS_NAME, REMARK, MODIFYUSER, UPDATETIME, FIRST_PUBLISH_DATE, AVGRESTIME, MAXRESTIME, MAXCONNUM, TIMEOUT, SUCCESSRATE, OUTMAXCONNUM, SECOND_PUBLISH_DATE)
  VALUES('0362', 'saphr', 'SAP人力系统', '', NULL, NULL, '20140710', '150000', NULL, 2, '300000', '90', NULL, NULL)
;
COMMIT;
COMMIT;
