DROP TABLE ESB.OLA_HISTORY;
CREATE TABLE ESB.OLA_HISTORY  ( 
	OPERATION_ID     	VARCHAR(255) NOT NULL,
	SERVICE_ID       	VARCHAR(40) NOT NULL,
	OPERATION_VERSION	VARCHAR(255) NOT NULL,
	SERVICE_VERSION  	VARCHAR(50) NOT NULL,
	OLA_NAME         	VARCHAR(100) NOT NULL,
	OLA_VALUE        	VARCHAR(255) NOT NULL,
	OLA_REMARK       	VARCHAR(500),
	MODIFYUSER       	VARCHAR(50),
	UPDATETIME       	VARCHAR(50) 
	)
;
COMMENT ON TABLE ESB.OLA_HISTORY IS '操作水平协议历史表'
;
COMMIT;
COMMIT;
COMMIT;
