DROP TABLE ESB.REMAINING_SERVICE;
CREATE TABLE ESB.REMAINING_SERVICE  ( 
	SERVICEID  	VARCHAR(255) NOT NULL,
	OPERATIONID	VARCHAR(100) NOT NULL 
	)
;
COMMENT ON TABLE ESB.REMAINING_SERVICE IS '旧WSDL服务操作信息表'
;
COMMENT ON COLUMN ESB.REMAINING_SERVICE.SERVICEID IS '服务ID'
;
COMMENT ON COLUMN ESB.REMAINING_SERVICE.OPERATIONID IS '操作ID'
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120030017', 'AcctComphCtrStQuery')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120030013', 'AuthrQuery')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120030017', 'AcctComphCtrDtlQuery')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S060020001', 'BidtlPrcsMtlCashColl')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120010003', 'ExtSnglTfr')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120050001', 'RcnclFileSvc')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120030004', 'SetlAcctInfoQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120030003', 'DaytimeTranQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120010002', 'AcctComphCtrSignRqs')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120010002', 'AcctComphCtrCnclRqs')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120020001', 'InrAcctOpen')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120030004', 'InternalAcctInfoQuery')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120010003', 'OneDbMoreCrTfr')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120010003', 'OneCrMoreDbTfr')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120020002', 'MMPPFcnOpnCls')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090020006', 'PndgTradeCncl')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090010005', 'TradeEntry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S040030001', 'CardInfoQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090010005', 'TradeLqd')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030010', 'SaleListQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030010', 'SaleRecordRePrt')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030010', 'SaleListHistRecordQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030012', 'PndgTradeQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120030004', 'AcctInfoQryByAcctNo')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030012', 'OrdrQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120030003', 'MMPPDaytimeTranQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S020030001', 'FdcrPayCtlAmtQuery')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090010004', 'SpotSale')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090010004', 'Presale')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090020003', 'TranInBank')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090020003', 'NormalInBank')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090020003', 'TranOutBank')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090020003', 'NormalOutBank')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090020003', 'DstrInBank')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030004', 'CtrDtlQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090010007', 'StopPftLossPndg')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090010007', 'PndgTradeEntry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030013', 'CrnClntHldsRskInfoQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030011', 'QtnQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030011', 'PdInfoList')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030011', 'PdParmQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030017', 'ClntInfoQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030014', 'ClntFrcExtInfoQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030014', 'AddMrgnFrcExtInfmQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030014', 'FrcExtClntRskInfoQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030014', 'FrcExtRskHldsQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090020002', 'AgrmSign')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030015', 'AgrmInfoQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030004', 'CtrListQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090020009', 'AgrmMnt')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090020002', 'AgrmUnwind')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090010006', 'MrgnAcctTfrIn')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090010006', 'MrgnAcctTfrOut')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030016', 'MrgnOptDtlQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030016', 'MrgnAcctDtlQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030016', 'MrgnAcctListQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030016', 'MrgnAcctQryByType')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090020004', 'DetailDlv')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090020004', 'SaleDlvReInpt')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090040001', 'RvrsSale')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030006', 'TranOutBankQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030006', 'TranOutBankDtlQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090020007', 'BranchReturnGoods')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030005', 'PdPriceQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030006', 'NormalInBankQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120030002', 'InstInfoQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030006', 'NormalInBankDtlQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030005', 'PdDtlQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030018', 'PvdrInfoQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030018', 'PvdrInvCmntQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120040001', 'RvrsTran')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030019', 'DlvRecordQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120030014', 'EmpUpdateInfoQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090020008', 'MblVerfCode')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030007', 'NoDlvMblNumPrepModRecordQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090020005', 'ModNoDlvMblNum')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030006', 'TranInBankQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030006', 'TranInBankDtlQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120020008', 'AddCorpClntInfo')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120020008', 'AddCorpAlias')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120020008', 'AddCorpRgstCptl')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120020008', 'CorpnClntInfoSync')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120030010', 'RtlBscInfoQryCtf')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120020007', 'RtlClntInfoSync')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120030009', 'DmstComPayeeQuery')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120020009', 'ClntSignInfoSync')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120020009', 'ClntInfoSync')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120020002', 'ChangeSignAcct')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120030010', 'RtlAsmbInfoQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120030010', 'RtlAsmbInfoQryCtf')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030005', 'SalePdQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030007', 'MblNumModHistRecordQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030006', 'TransferQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030006', 'StockQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030005', 'GainSalesDiscountRate')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030005', 'HistPriceQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030020', 'AgrtListQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030019', 'DlvHistRecordQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120020002', 'CorpFncgSignInfoMnt')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120020002', 'IdvBankFncgSignInfoMnt')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030022', 'TlrTranDtlQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030015', 'AgrmInfoQryAsmbCd')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030016', 'MrgnOptDtlQryAsmbCd')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030016', 'MrgnAcctDtlQryAsmbCd')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120030005', 'AcctOtherSysSignInfoQuery')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120030005', 'TvBankSignInfoQuery')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120030005', 'FundAcctOpenInfoQuery')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120030021', 'InstInfoDtlQry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120030005', 'FncgBindAcctListQuery')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120030005', 'FncgCrfmDtlQuery')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120020001', 'ExgFncgAcctOpen')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120020001', 'MrgnDepAcctOpen')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120010001', 'AcctBlock')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120030003', 'ComphAcctTranDtlQuery')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120030004', 'FundAcctInfoQuery')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120030004', 'AcctInfoQuery')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120030004', 'CorpCrnAcctQuery')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S010020001', 'DepTfrAgrmMnt')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120020005', 'MktClueMnt')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120030002', 'InstListQuery')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S030010002', 'BillInAcct')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120030008', 'IntRateQuery')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030002', 'FncgPdDtlQuery')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030001', 'FncgAcctTranDtlQuery')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030001', 'FundApplyTranDtlQuery')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030001', 'FundCrfmTranDtlQuery')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090010001', 'FncgPdPrch')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090010001', 'FncgPdApplyPrch')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090010001', 'BankFundSysPrch')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090010001', 'BankFundSysApplyPrch')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120030007', 'ClientMktClueDtl')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120030007', 'ClientMktClueQuery')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120020004', 'ClientMktResult')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120030001', 'TellerTranDtlPrint')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120020006', 'MsgInfomMnt')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120020006', 'MsgSendSvc')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120020003', 'MsgOrEmailSignInfoMnt')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S020010001', 'NormalLoanDstr')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S020010001', 'FdcrPayAutoEntry')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S020040001', 'FdcrPayTranRvrs')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120040001', 'EraseAcct')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S010010001', 'BankAcptMrgnOpenAndDep')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090010002', 'PrtflApplyPrch')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090020001', 'PrtflTrackInfMnt')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120050001', 'TaskInfoService')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120030003', 'TranDtlFuzzyQuery')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120050001', 'FileUploadInform')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120030005', 'ExgFncgAcctOpenQuery')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030002', 'ExgFncPdInfoQuery')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090010006', '0000')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030022', '0000')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030016', '0000')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030004', '0000')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090010003', '0000')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030021', '0000')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090030015', '0000')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090020002', '0000')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090020009', '0000')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S090050001', '0000')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120030011', '0000')
;
INSERT INTO ESB.REMAINING_SERVICE(SERVICEID, OPERATIONID)
  VALUES('S120030016', '0000')
;
COMMIT;
COMMIT;
COMMIT;
