DROP TABLE ESB.SLA_HISTORY;
CREATE TABLE ESB.SLA_HISTORY  ( 
	SERVICE_ID       	VARCHAR(255) NOT NULL,
	SERVICE_VERSION  	VARCHAR(50) NOT NULL,
	OPERATION_ID     	VARCHAR(255) NOT NULL,
	OPERATION_VERSION	VARCHAR(255) NOT NULL,
	SLA_NAME         	VARCHAR(255) NOT NULL,
	SLA_VALUE        	VARCHAR(50),
	SLA_REMARK       	VARCHAR(500),
	MODIFYUSER       	VARCHAR(50),
	UPDATETIME       	VARCHAR(50) 
	)
;
COMMENT ON TABLE ESB.SLA_HISTORY IS '服务水平协议历史表'
;
COMMIT;
COMMIT;
COMMIT;
