DROP TABLE  AUDITSTATE;
CREATE TABLE  AUDITSTATE  ( 
	ID   	VARCHAR(25) NOT NULL,
	STATE	VARCHAR(40) NOT NULL 
	)
;
COMMENT ON TABLE  AUDITSTATE IS 'ÉóºË×´Ì¬±í'
;
COMMENT ON COLUMN  AUDITSTATE.ID IS 'IDÖ÷¼ü'
;
COMMENT ON COLUMN  AUDITSTATE.STATE IS 'ÉóºË×´Ì¬'
;
INSERT INTO  AUDITSTATE(ID, STATE)
  VALUES('0', 'ÐÂÔö')
;
INSERT INTO  AUDITSTATE(ID, STATE)
  VALUES('1', '´ýÉóºË')
;
INSERT INTO  AUDITSTATE(ID, STATE)
  VALUES('2', 'Í¨¹ý')
;
INSERT INTO  AUDITSTATE(ID, STATE)
  VALUES('3', '¾Ü¾ø')
;
COMMIT;
COMMIT;
