DROP TABLE  DEFAULT_SERVICE;
CREATE TABLE  DEFAULT_SERVICE  ( 
	SERVICE_ID    	VARCHAR(255) NOT NULL,
	SERVICE_NAME  	VARCHAR(255),
	SERVICE_REMARK	VARCHAR(500) 
	)
;
COMMENT ON TABLE  DEFAULT_SERVICE IS '默认服务信息表'
;
COMMENT ON COLUMN  DEFAULT_SERVICE.SERVICE_ID IS '服务ID'
;
COMMENT ON COLUMN  DEFAULT_SERVICE.SERVICE_NAME IS '服务名称'
;
COMMENT ON COLUMN  DEFAULT_SERVICE.SERVICE_REMARK IS '服务描述'
;
INSERT INTO  DEFAULT_SERVICE(SERVICE_ID, SERVICE_NAME, SERVICE_REMARK)
  VALUES('SHEAD', '业务报文头', '业务报文头')
;
INSERT INTO  DEFAULT_SERVICE(SERVICE_ID, SERVICE_NAME, SERVICE_REMARK)
  VALUES('SHEAD1', '业务报文头1', '业务报文头1')
;
INSERT INTO  DEFAULT_SERVICE(SERVICE_ID, SERVICE_NAME, SERVICE_REMARK)
  VALUES('SHEAD2', '业务报文头2', '业务报文头2')
;
INSERT INTO  DEFAULT_SERVICE(SERVICE_ID, SERVICE_NAME, SERVICE_REMARK)
  VALUES('SOPAbstractService', 'SOPAbstractService', 'SOPAbstractService')
;
COMMIT;
COMMIT;
