@/home/oracle/sg_sql/AUDITSTATE.sql
@/home/oracle/sg_sql/DEFAULT_INTERFACE.sql
@/home/oracle/sg_sql/DEFAULT_SERVICE.sql
@/home/oracle/sg_sql/HEADSDA.sql
@/home/oracle/sg_sql/IDA.sql
@/home/oracle/sg_sql/IDA_BAK.sql
@/home/oracle/sg_sql/IDA_PROP.sql
@/home/oracle/sg_sql/INTERFACE.sql
@/home/oracle/sg_sql/INTERFACE_EXTENDS.sql
@/home/oracle/sg_sql/INVOKE_RELATION.sql
@/home/oracle/sg_sql/METADATA.sql
@/home/oracle/sg_sql/METADATA_STRUCTS.sql
@/home/oracle/sg_sql/METADATA_STRUCTS_ATTR.sql
@/home/oracle/sg_sql/METADATA_STRUCTS_EXPRESSSION.sql
@/home/oracle/sg_sql/OLA.sql
@/home/oracle/sg_sql/OLA_HISTORY.sql
@/home/oracle/sg_sql/OPERATION_HISTORY.sql
@/home/oracle/sg_sql/PROTOCOLINFO.sql
@/home/oracle/sg_sql/PUBLISH_INFO.sql
@/home/oracle/sg_sql/REMAINING_SERVICE.sql
@/home/oracle/sg_sql/SDA.sql
@/home/oracle/sg_sql/SDA_HISTORY.sql
@/home/oracle/sg_sql/SDA_PROP.sql
@/home/oracle/sg_sql/SERVICE.sql
@/home/oracle/sg_sql/SERVICE_CATEGORY.sql
@/home/oracle/sg_sql/SERVICE_HEAD_RELATE.sql
@/home/oracle/sg_sql/SG_FUNCTION.sql
@/home/oracle/sg_sql/SG_LOG.sql
@/home/oracle/sg_sql/SG_OPERATION.sql
@/home/oracle/sg_sql/SG_ORG.sql
@/home/oracle/sg_sql/SG_ROLE.sql
@/home/oracle/sg_sql/SG_ROLE_FUNCTION_RELATE.sql
@/home/oracle/sg_sql/SG_SLA.sql
@/home/oracle/sg_sql/SG_SYSTEM.sql
@/home/oracle/sg_sql/SG_USER.sql
@/home/oracle/sg_sql/SLA_HISTORY.sql
@/home/oracle/sg_sql/TRANS_STATE.sql
