CREATE VIEW "ESB"."RELATION_PASSED_VIEW"
as
(select concat(ir.OPERATION_ID,ir.SERVICE_ID) as os,ir.OPERATION_ID,ir.SERVICE_ID,ir.PROVIDE_SYS_ID,ir.CONSUME_SYS_ID,ir.CONSUME_MSG_TYPE,ir.PROVIDE_MSG_TYPE,ts.VERSIONST from INVOKE_RELATION ir 
left join TRANS_STATE ts on ir.ID = ts.ID 
left join SG_OPERATION o on ir.OPERATION_ID = o.OPERATION_ID 
left join SERVICE s on ir.SERVICE_ID = s.SERVICE_ID 
where o.AUDITSTATE='2' and s.AUDITSTATE ='2'
)