INSERT INTO ESB.SG_ROLE (ROLE_ID, ROLE_NAME, ROLE_REMARK) VALUES (1, '管理员', '管理员');
INSERT INTO ESB.SG_ROLE (ROLE_ID, ROLE_NAME, ROLE_REMARK) VALUES (2, '服务审核人员', '服务审核人员');
INSERT INTO ESB.SG_ROLE (ROLE_ID, ROLE_NAME, ROLE_REMARK) VALUES (3, '服务定义人员', '进行业务分析、服务的定义与发布');
INSERT INTO ESB.SG_ROLE (ROLE_ID, ROLE_NAME, ROLE_REMARK) VALUES (4, '配置开发人员', '对已发布的服务进行开发配置');
INSERT INTO ESB.SG_ROLE (ROLE_ID, ROLE_NAME, ROLE_REMARK) VALUES (5, '接入系统开发人员', '接入系统开发人员');
INSERT INTO ESB.SG_ROLE (ROLE_ID, ROLE_NAME, ROLE_REMARK) VALUES (6, '访客', '访客');
