INSERT INTO ESB.AUDITSTATE (ID, STATE) VALUES ('0', '新增');
INSERT INTO ESB.AUDITSTATE (ID, STATE) VALUES ('1', '待审核');
INSERT INTO ESB.AUDITSTATE (ID, STATE) VALUES ('2', '通过');
INSERT INTO ESB.AUDITSTATE (ID, STATE) VALUES ('3', '拒绝');
