INSERT INTO ESB.SG_SLA (SERVICE_ID, OPERATION_ID, SLA_NAME, SLA_VALUE, SLA_REMARK, MODIFYUSER, UPDATETIME) VALUES ('04005000001', '01', '并发数', '500', null, null, null);
INSERT INTO ESB.SG_SLA (SERVICE_ID, OPERATION_ID, SLA_NAME, SLA_VALUE, SLA_REMARK, MODIFYUSER, UPDATETIME) VALUES ('11003000008', '01', '并发数', '500', null, null, null);
