DROP TABLE ESB.AUDITSTATE;
CREATE TABLE ESB.AUDITSTATE  ( 
	ID   	VARCHAR(25) NOT NULL,
	STATE	VARCHAR(40) NOT NULL 
	)
;
COMMENT ON TABLE ESB.AUDITSTATE IS '审核状态表'
;
COMMENT ON COLUMN ESB.AUDITSTATE.ID IS 'ID主键'
;
COMMENT ON COLUMN ESB.AUDITSTATE.STATE IS '审核状态'
;
INSERT INTO ESB.AUDITSTATE(ID, STATE)
  VALUES('0', '新增')
;
INSERT INTO ESB.AUDITSTATE(ID, STATE)
  VALUES('1', '待审核')
;
INSERT INTO ESB.AUDITSTATE(ID, STATE)
  VALUES('2', '通过')
;
INSERT INTO ESB.AUDITSTATE(ID, STATE)
  VALUES('3', '拒绝')
;
COMMIT;
