DROP TABLE ESB.SG_USER;
CREATE TABLE ESB.SG_USER  ( 
	USER_ID      	INTEGER NOT NULL,
	USER_NAME    	VARCHAR(255) NOT NULL,
	USER_PASSWORD	VARCHAR(255) NOT NULL,
	USER_ROLE_ID 	INTEGER NOT NULL,
	USER_ORG_ID  	VARCHAR(255) NOT NULL,
	USER_LASTDATE	VARCHAR(255),
	USER_REMARK  	VARCHAR(255),
	USER_STATUS  	VARCHAR(255) NOT NULL 
	)
;
COMMENT ON TABLE ESB.SG_USER IS '用户基本信息表'
;
COMMENT ON COLUMN ESB.SG_USER.USER_ID IS '用户ID'
;
COMMENT ON COLUMN ESB.SG_USER.USER_NAME IS '用户名'
;
COMMENT ON COLUMN ESB.SG_USER.USER_PASSWORD IS '密码'
;
COMMENT ON COLUMN ESB.SG_USER.USER_ROLE_ID IS '角色ID'
;
COMMENT ON COLUMN ESB.SG_USER.USER_ORG_ID IS '机构ID'
;
COMMENT ON COLUMN ESB.SG_USER.USER_LASTDATE IS '最后登录日期'
;
COMMENT ON COLUMN ESB.SG_USER.USER_REMARK IS '描述'
;
COMMENT ON COLUMN ESB.SG_USER.USER_STATUS IS '状态'
;
INSERT INTO ESB.SG_USER(USER_ID, USER_NAME, USER_PASSWORD, USER_ROLE_ID, USER_ORG_ID, USER_LASTDATE, USER_REMARK, USER_STATUS)
  VALUES(1, 'admin', '111', 1, '0020', '20141106 15:42:00', '管理员', '1')
;
INSERT INTO ESB.SG_USER(USER_ID, USER_NAME, USER_PASSWORD, USER_ROLE_ID, USER_ORG_ID, USER_LASTDATE, USER_REMARK, USER_STATUS)
  VALUES(2, 'xiayn', 'spdb1234', 4, '0200', '', '', '1')
;
INSERT INTO ESB.SG_USER(USER_ID, USER_NAME, USER_PASSWORD, USER_ROLE_ID, USER_ORG_ID, USER_LASTDATE, USER_REMARK, USER_STATUS)
  VALUES(3, 'wanglr', 'spdb1234', 2, '0200', '', '', '1')
;
INSERT INTO ESB.SG_USER(USER_ID, USER_NAME, USER_PASSWORD, USER_ROLE_ID, USER_ORG_ID, USER_LASTDATE, USER_REMARK, USER_STATUS)
  VALUES(4, 'zhangm', 'spdb1234', 3, '0200', '', '', '1')
;
INSERT INTO ESB.SG_USER(USER_ID, USER_NAME, USER_PASSWORD, USER_ROLE_ID, USER_ORG_ID, USER_LASTDATE, USER_REMARK, USER_STATUS)
  VALUES(5, 'wangyy', 'spdb1234', 3, '0200', '', '', '1')
;
INSERT INTO ESB.SG_USER(USER_ID, USER_NAME, USER_PASSWORD, USER_ROLE_ID, USER_ORG_ID, USER_LASTDATE, USER_REMARK, USER_STATUS)
  VALUES(6, 'heqy', 'spdb1234', 3, '0200', '', '', '1')
;
INSERT INTO ESB.SG_USER(USER_ID, USER_NAME, USER_PASSWORD, USER_ROLE_ID, USER_ORG_ID, USER_LASTDATE, USER_REMARK, USER_STATUS)
  VALUES(7, 'luozm', 'spdb1234', 4, '0200', '', '', '1')
;
INSERT INTO ESB.SG_USER(USER_ID, USER_NAME, USER_PASSWORD, USER_ROLE_ID, USER_ORG_ID, USER_LASTDATE, USER_REMARK, USER_STATUS)
  VALUES(8, 'zhangh', 'spdb1234', 4, '0200', '', '', '1')
;
INSERT INTO ESB.SG_USER(USER_ID, USER_NAME, USER_PASSWORD, USER_ROLE_ID, USER_ORG_ID, USER_LASTDATE, USER_REMARK, USER_STATUS)
  VALUES(9, 'zhul', 'spdb1234', 4, '0200', '', '', '1')
;
INSERT INTO ESB.SG_USER(USER_ID, USER_NAME, USER_PASSWORD, USER_ROLE_ID, USER_ORG_ID, USER_LASTDATE, USER_REMARK, USER_STATUS)
  VALUES(10, 'gaoc', 'spdb1234', 4, '0200', '', '', '1')
;
INSERT INTO ESB.SG_USER(USER_ID, USER_NAME, USER_PASSWORD, USER_ROLE_ID, USER_ORG_ID, USER_LASTDATE, USER_REMARK, USER_STATUS)
  VALUES(11, 'jixl', 'spdb1234', 4, '0200', '', '', '1')
;
INSERT INTO ESB.SG_USER(USER_ID, USER_NAME, USER_PASSWORD, USER_ROLE_ID, USER_ORG_ID, USER_LASTDATE, USER_REMARK, USER_STATUS)
  VALUES(12, 'guiqh', 'spdb1234', 4, '0200', '', '', '1')
;
INSERT INTO ESB.SG_USER(USER_ID, USER_NAME, USER_PASSWORD, USER_ROLE_ID, USER_ORG_ID, USER_LASTDATE, USER_REMARK, USER_STATUS)
  VALUES(13, 'lk', 'spdb1234', 4, '0200', '', '', '1')
;
INSERT INTO ESB.SG_USER(USER_ID, USER_NAME, USER_PASSWORD, USER_ROLE_ID, USER_ORG_ID, USER_LASTDATE, USER_REMARK, USER_STATUS)
  VALUES(14, 'zugq', 'spdb1234', 4, '0200', '', '', '1')
;
COMMIT;
