DROP TABLE ESB.METADATA_STRUCTS_EXPRESSSION;
CREATE TABLE ESB.METADATA_STRUCTS_EXPRESSSION  ( 
	STRUCTID      	VARCHAR(50) NOT NULL,
	ELEMENTID     	VARCHAR(100) NOT NULL,
	ATTRIBUTEID   	VARCHAR(100),
	ATTRIBUTEVALUE	VARCHAR(255) 
	)
;
COMMENT ON TABLE ESB.METADATA_STRUCTS_EXPRESSSION IS '元数据结构表达式表'
;
COMMENT ON COLUMN ESB.METADATA_STRUCTS_EXPRESSSION.STRUCTID IS '结构体ID'
;
COMMENT ON COLUMN ESB.METADATA_STRUCTS_EXPRESSSION.ELEMENTID IS '元数据ID'
;
COMMENT ON COLUMN ESB.METADATA_STRUCTS_EXPRESSSION.ATTRIBUTEID IS '属性ID'
;
COMMENT ON COLUMN ESB.METADATA_STRUCTS_EXPRESSSION.ATTRIBUTEVALUE IS '属性值'
;
INSERT INTO ESB.METADATA_STRUCTS_EXPRESSSION(STRUCTID, ELEMENTID, ATTRIBUTEID, ATTRIBUTEVALUE)
  VALUES('Xperson', 'OrgCharticTpCd', 'expression', '$codeConvert:(slaveCode:：CompanyChar_01,masterCode:CompanyChar,serviceNodePath:$XPath,whateverItisa1:1)')
;
INSERT INTO ESB.METADATA_STRUCTS_EXPRESSSION(STRUCTID, ELEMENTID, ATTRIBUTEID, ATTRIBUTEVALUE)
  VALUES('Xperson', 'OccupationTpCd', 'expression', '$codeConvert:(slaveCode:：OcpCode_01,masterCode:OcpCode,serviceNodePath:$XPath,whateverItisa1:1)')
;
COMMIT;
