DROP TABLE ESB.SDA_PROP;
CREATE TABLE ESB.SDA_PROP  ( 
	ID           	VARCHAR(100) NOT NULL,
	SDA_ID       	VARCHAR(100) NOT NULL,
	PROPERTYNAME 	VARCHAR(100) NOT NULL,
	PROPERTYVALUE	VARCHAR(255) NOT NULL,
	REMARK       	VARCHAR(500),
	SEQ          	INTEGER,
	VERSIONNO    	VARCHAR(40),
	UPDATEDATE   	VARCHAR(40),
	VERSIONST    	VARCHAR(40),
	PRODUCTNO    	VARCHAR(40) 
	)
;
COMMENT ON TABLE ESB.SDA_PROP IS 'SDA属性信息表'
;
COMMIT;
