DROP TABLE ESB.SG_ROLE_FUNCTION_RELATE;
CREATE TABLE ESB.SG_ROLE_FUNCTION_RELATE  ( 
	ROLE_ID    	INTEGER NOT NULL,
	FUNCTION_ID	INTEGER NOT NULL 
	)
;
COMMENT ON TABLE ESB.SG_ROLE_FUNCTION_RELATE IS '角色功能关联表'
;
COMMENT ON COLUMN ESB.SG_ROLE_FUNCTION_RELATE.ROLE_ID IS '角色ID'
;
COMMENT ON COLUMN ESB.SG_ROLE_FUNCTION_RELATE.FUNCTION_ID IS '菜单ID'
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(1, 1)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(1, 2)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(1, 3)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(1, 4)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(1, 5)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(1, 6)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(1, 7)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(1, 8)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(1, 9)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(1, 10)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(1, 11)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(1, 12)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(1, 13)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(1, 14)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(1, 15)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(1, 16)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(1, 17)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(1, 18)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(1, 19)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(1, 20)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(1, 21)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(1, 22)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(1, 23)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(1, 24)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(1, 25)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(1, 26)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(1, 28)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(1, 29)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(1, 30)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(1, 31)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(1, 32)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(1, 33)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(1, 34)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(1, 35)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(1, 36)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(1, 37)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(1, 38)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(2, 1)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(2, 2)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(2, 3)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(2, 4)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(2, 5)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(2, 6)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(2, 7)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(2, 8)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(2, 9)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(2, 10)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(2, 11)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(2, 12)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(2, 13)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(2, 14)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(2, 15)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(2, 16)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(2, 17)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(2, 18)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(2, 19)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(2, 20)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(2, 21)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(2, 22)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(2, 23)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(2, 24)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(2, 25)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(2, 26)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(2, 28)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(2, 33)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(2, 34)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(3, 1)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(3, 2)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(3, 3)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(3, 4)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(3, 5)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(3, 6)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(3, 7)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(3, 8)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(3, 9)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(3, 10)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(3, 11)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(3, 12)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(3, 13)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(3, 14)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(3, 15)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(3, 16)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(3, 17)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(3, 18)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(3, 19)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(3, 20)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(3, 21)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(3, 22)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(3, 23)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(3, 24)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(3, 25)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(3, 26)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(3, 28)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(3, 33)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(3, 34)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(4, 1)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(4, 2)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(4, 3)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(4, 4)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(4, 5)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(4, 6)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(4, 7)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(4, 8)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(4, 9)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(4, 10)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(4, 11)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(4, 12)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(4, 13)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(4, 15)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(4, 16)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(4, 17)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(4, 18)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(4, 19)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(4, 20)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(4, 21)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(4, 22)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(4, 23)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(4, 24)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(4, 25)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(4, 26)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(4, 28)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(4, 33)
;
INSERT INTO ESB.SG_ROLE_FUNCTION_RELATE(ROLE_ID, FUNCTION_ID)
  VALUES(4, 34)
;
COMMIT;
