DROP TABLE  METADATA_STRUCTS_ATTR;
CREATE TABLE  METADATA_STRUCTS_ATTR  ( 
	STRUCTID   	VARCHAR(50) NOT NULL,
	ELEMENTID  	VARCHAR(50),
	ELEMENTNAME	VARCHAR(100),
	REMARK     	VARCHAR(500),
	ISREQUIRED 	VARCHAR(10),
	METADATAID 	VARCHAR(50) NOT NULL 
	)
;
COMMENT ON TABLE  METADATA_STRUCTS_ATTR IS '元数据结构体属性信息表'
;
COMMENT ON COLUMN  METADATA_STRUCTS_ATTR.STRUCTID IS '结构体ID'
;
COMMENT ON COLUMN  METADATA_STRUCTS_ATTR.ELEMENTID IS '原始元数据ID'
;
COMMENT ON COLUMN  METADATA_STRUCTS_ATTR.ELEMENTNAME IS '原始元数据名称'
;
COMMENT ON COLUMN  METADATA_STRUCTS_ATTR.REMARK IS '描述'
;
COMMENT ON COLUMN  METADATA_STRUCTS_ATTR.ISREQUIRED IS '是否必输'
;
COMMENT ON COLUMN  METADATA_STRUCTS_ATTR.METADATAID IS '元数据ID'
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('BPMPageInfo', 'CountFlag', '统计标志', 'Y/N默认不统计总数', 'Y', 'CountFlag')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('BPMPageInfo', 'PageNum', '每页笔数', 'null', 'Y', 'PageNum')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('BPMPageInfo', 'StartNum1', '起始笔数1', '查询从第begin到begin+ pageSize之间的记录', 'Y', 'StartNum1')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ChildFrontFunc', 'ChildFrontFunc', '子功能点', 'ChildFrontFunc', '', 'ChildFrontFunc')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ChildFrontFunc', 'ExtendDest', '扩展目标', '', '', 'ExnTarget')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ChildFrontFunc', 'FuncId', '前端功能点ID', '', '', 'FuncId1')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ChildFrontFunc', 'FuncName', '前端功能点名称', '', '', 'FuncName')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ChildFrontFunc', 'FuncDest', '前端功能点目标', '', '', 'FuncTarget')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ChildFrontFunc', 'RoleId', '所属角色ID', '', '', 'RoleId1')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ChildFrontFunc', 'FFuncRoleExtendDest', '角色关系的目标', '', '', 'RoleRelTrgt')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ChildFrontFunc', 'Status', '状态', '', '', 'Status')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ChildGrpList', 'ChildGroupList', '子用户组信息列表', 'ChildGroupList', '', 'ChildGrpList')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ChildGrpList', 'ChildOrgs', '子机构列表', 'ChildOrgs', '', 'ChildInsts')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ChildGrpList', 'FrontFuncInfoList', '前端功能列表', 'FrontFuncInfoList', '', 'FrontFuncInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ChildGrpList', 'GroupId', '用户组ID', '', '', 'GroupId')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ChildGrpList', 'GroupName', '用户组名称', '', '', 'GroupName')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ChildGrpList', 'HLevel', '用户组HLevel', '', '', 'HLevel')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ChildGrpList', 'Description', '用户组描述', '', '', 'Remark')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ChildGrpList', 'RoleInfoList', '角色信息列表', 'RoleInfoList', '', 'RoleInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ChildGrpList', 'TaskInfoList', '任务信息列表', 'TaskInfoList', '', 'TaskInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ChildGrpList', 'UserExtendedInfoXml', '用户自定义属性', '', '', 'UserExnAttr')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ChildInsts', 'BranchId', '分行代码', '', '', 'BranchId')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ChildInsts', 'ChildGroupList', '子用户组信息列表', 'ChildGroupList', '', 'ChildGrpList')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ChildInsts', 'ChildOrgs', '子机构列表', 'ChildOrgs', '', 'ChildInsts')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ChildInsts', 'CountryCode', '国家代码', '', '', 'CountryCode')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ChildInsts', 'FrontFuncInfoList', '前端功能列表', 'FrontFuncInfoList', '', 'FrontFuncInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ChildInsts', 'HLevel', '机构的HLevel', '', '', 'HLevel')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ChildInsts', 'OrgExtendedInfoXml', '机构自定义属性', '', '', 'InstExnAttr')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ChildInsts', 'OrgId', '机构ID', '', '', 'InstId1')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ChildInsts', 'OrgName', '机构名称', '', '', 'InstName')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ChildInsts', 'OrgType', '机构类型', '', '', 'InstType')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ChildInsts', 'Description', '注释', '', '', 'Remark')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ChildInsts', 'RoleInfoList', '角色信息列表', 'RoleInfoList', '', 'RoleInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ChildInsts', 'TaskInfoList', '任务信息列表', 'TaskInfoList', '', 'TaskInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ChildInsts', 'TreeType', '所属机构树类型', '', '', 'TreeType')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ChildInsts', 'UserExtendedInfoXml', '用户自定义属性', '', '', 'UserExnAttr')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ChildTasks', 'ChildTasks', '子任务列表', 'ChildTasks', '', 'ChildTasks')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ChildTasks', 'TaskDestination', '任务代码', '', '', 'TaskCode')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ChildTasks', 'TaskId', '任务ID', '', '', 'TaskId1')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ChildTasks', 'TaskName', '任务名称', '', '', 'TaskName')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ClntComInfo', 'Address', '地址信息(对象)', 'Address', '', 'AdrInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ClntComInfo', 'CheckInd', '复核标识', '', 'N', 'CheckFlag')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ClntComInfo', 'ClientName', '客户名称', '', 'Y', 'ClientName')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ClntComInfo', 'ClientStTpCd', '客户状态', '', 'N', 'ClientStatus')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ClntComInfo', 'ClientCode', '客户类型', '', 'N', 'ClientType')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ClntComInfo', 'LangTpCd', '通讯语言', '', 'N', 'CmmLangCode')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ClntComInfo', 'ComPayeeDmst', '常用收款人(人民币)信息(对象)', 'ComPayeeDmst', '', 'ComPayeeDmst')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ClntComInfo', 'ComPayeeOvs', '常用收款人(境外/外币)信息(对象)', 'ComPayeeOvs', '', 'ComPayeeOvs')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ClntComInfo', 'CreateInst', '建立机构', '', 'N', 'CreateBranchId1')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ClntComInfo', 'CreateTlr', '建立柜员', '', 'N', 'CreateTellerNo1')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ClntComInfo', 'CreateTms', '建立时间戳', '', 'N', 'CreateTimep1')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ClntComInfo', 'ContactMethod', '联系方式信息(对象)', 'ContactMethod', '', 'CtcModeInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ClntComInfo', 'Identifier', '证件信息(对象)', 'Identifier', '', 'CtfInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ClntComInfo', 'ClientId', '客户内部序号', '', 'N', 'ECIFClientNo1')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ClntComInfo', 'Finance', '客户财务信息(对象)', 'Finance', '', 'FncInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ClntComInfo', 'ClientLevel', '客户等级信息(对象)', 'ClientLevel', '', 'LevelInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ClntComInfo', 'Manager', '客户管理人员信息(对象)', 'Manager', '', 'MgrInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ClntComInfo', 'OffshoreInd', '离岸客户标识', '', 'N', 'OffshrFlag')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ClntComInfo', 'ClientAttr', '客户其他属性信息(对象)', 'ClientAttr', '', 'OthrAttrInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ClntComInfo', 'DevelopEmpNo', '开拓人(员工编号)', '', 'N', 'PioneerNo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ClntComInfo', 'RelatedPerson', '客户关联人信息(对象)', 'RelatedPerson', '', 'RelClntInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ClntComInfo', 'InfoIntegFlag', '信息完整性标识', '', 'N', 'Remark1')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ClntComInfo', 'RiskLevel', '客户风险信息(对象)', 'RiskLevel', '', 'RiskLevelInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ClntComInfo', 'ClientRel', '客户关系信息(对象)', 'ClientRel', '', 'RltnpInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ClntComInfo', 'PremCountryTpCd', '常驻国家', '', 'N', 'RsdntCtyCode')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ClntComInfo', 'ResidentTpCd', '居民类型', '', 'N', 'RsdntType')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ClntComInfo', 'SpecialList', '客户特殊名单信息(对象)', 'SpecialList', '', 'SpclListInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ComPayeeDmst', 'ActiveInd', '活动标识', 'Y：有效
N：无效', 'N', 'ActiveFlag')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ComPayeeDmst', 'ClientId', '客户(汇款人)内部序号', '', 'N', 'ECIFClientNo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ComPayeeDmst', 'PayeeAcctNo', '收款人账号', '', 'N', 'PayeeAcctNo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ComPayeeDmst', 'PayeeAcctType', '收款人账号类型', '账号类型（1:银行卡、2:email、3:手机号、4:地址）', 'N', 'PayeeAcctNoType')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ComPayeeDmst', 'PayeeAcctStatus', '账户状态', '0-正常
1-已删除', 'N', 'PayeeAcctStatus')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ComPayeeDmst', 'PayeeType', '收款人账户类型', '', 'N', 'PayeeAcctType')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ComPayeeDmst', 'PayeeAddress', '收款人地址', '', 'N', 'PayeeAdr')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ComPayeeDmst', 'PayeeBankPayNo', '收款银行现代支付号', '', 'N', 'PayeeAdvPayId')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ComPayeeDmst', 'PayeeInst', '收款方行号', '', 'N', 'PayeeBranchId')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ComPayeeDmst', 'PayeeBank', '收款银行名称', '', 'N', 'PayeeBranchName')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ComPayeeDmst', 'PayeeEmail', '收款人邮件', '', 'N', 'PayeeEmail')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ComPayeeDmst', 'PayeeMobile', '收款人手机', '', 'N', 'PayeeMobile')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ComPayeeDmst', 'PayeeName', '收款人名称', '', 'N', 'PayeeName')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ComPayeeDmst', 'PayeeId', '收款人内部序号', '', 'N', 'PayeeNo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ComPayeeDmst', 'PayeeQq', '收款人QQ', '', 'N', 'PayeeQQ')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ComPayeeDmst', 'PayeeSource', '收款人信息来源', '', 'N', 'PayeeSrc')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ComPayeeDmst', 'PayeeWechat', '收款人微信', '', 'N', 'PayeeWechat')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ComPayeeDmst', 'PayeeWeibo', '收款人微博', '', 'N', 'PayeeWeibo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ComPayeeDmst', 'PayeePostcode', '收款人邮编', '', 'N', 'PayeeZipCode')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ComPayeeDmst', 'RemitRouteTpCd', '汇路', '', 'N', 'RemitRoute')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ComPayeeDmst', 'PayeeFlag', '汇款类型', '网银汇款类型（11:行内汇款、12:普通汇款、13:实时汇款、14:信用卡跨行还款、15:汇到银联卡、20:email汇款、30:手机汇款、40:邮政汇款）', 'N', 'RemitType')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ComPayeeDmst', 'Reserve1', '预留字段1', '', 'N', 'RsrvField')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ComPayeeDmst', 'Reserve2', '预留字段2', '', 'N', 'RsrvField1')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ComPayeeOvs', 'ActiveInd', '活动标识', 'Y：有效
N：无效', 'N', 'ActiveFlag')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ComPayeeOvs', 'ClientId', '客户(汇款人)内部序号', '', 'N', 'ECIFClientNo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ComPayeeOvs', 'IntrBankBic', '中间行BIC号', '', 'N', 'InterBankBIC')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ComPayeeOvs', 'IntrBank', '中间行名称56', '', 'N', 'InterBankName')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ComPayeeOvs', 'PayeeAcctNo', '收款人账号59A', '', 'N', 'PayeeAcctNo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ComPayeeOvs', 'PayeeBankBic', '收款银行BIC号', '', 'N', 'PayeeBranchBIC')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ComPayeeOvs', 'PayeeBank', '收款银行名称57', '', 'N', 'PayeeBranchName')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ComPayeeOvs', 'PayeeName', '收款人名称', '', 'N', 'PayeeName')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ComPayeeOvs', 'PayeeId', '收款人内部序号', '', 'N', 'PayeeNo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ComPayeeOvs', 'PayeeSource', '收款人信息来源', '1：交易历史
2：网银收款人登记簿', 'N', 'PayeeSrc')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('ComPayeeOvs', 'RemitRouteTpCd', '汇路', '', 'N', 'RemitRoute')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'Address', '地址信息(对象)', 'Address', '', 'AdrInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'CheckInd', '复核标识', '', 'N', 'CheckFlag')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'ClientName', '客户名称', '', 'Y', 'ClientName')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'ClientStTpCd', '客户状态', '', 'N', 'ClientStatus')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'ClientCode', '客户类型', '', 'N', 'ClientType')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'LangTpCd', '通讯语言', '', 'N', 'CmmLangCode')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'OrgFormTpCd', '组织形式', '', 'N', 'CoFormType')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'OrgTpCd', '企业类型', '', 'N', 'CompanyType')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'ComPayeeDmst', '常用收款人(人民币)信息(对象)', 'ComPayeeDmst', '', 'ComPayeeDmst')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'ComPayeeOvs', '常用收款人(境外/外币)信息(对象)', 'ComPayeeOvs', '', 'ComPayeeOvs')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'OrgName', '企业客户名称信息(对象)', 'OrgName', '', 'CorpNameInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'CreateInst', '建立机构', '', 'N', 'CreateBranchId1')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'EstablishedDt', '成立日期', '', 'N', 'CreateDate')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'CreateTlr', '建立柜员', '', 'N', 'CreateTellerNo1')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'CreateTms', '建立时间戳', '', 'N', 'CreateTimep1')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'ContactMethod', '联系方式信息(对象)', 'ContactMethod', '', 'CtcModeInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'Identifier', '证件信息(对象)', 'Identifier', '', 'CtfInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'EconomicTpCd', '经济类型', '', 'N', 'EconomicChar')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'ClientId', '客户内部序号', '', 'N', 'ECIFClientNo1')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'FiInd', '金融机构标识', '', 'N', 'FIFlag')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'Finance', '客户财务信息(对象)', 'Finance', '', 'FncInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'IndustryTpCd', '行业类型', '', 'N', 'IndustryType')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'ClientLevel', '客户等级信息(对象)', 'ClientLevel', '', 'LevelInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'Manager', '客户管理人员信息(对象)', 'Manager', '', 'MgrInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'OffshoreInd', '离岸客户标识', '', 'N', 'OffshrFlag')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'ClientAttr', '客户其他属性信息(对象)', 'ClientAttr', '', 'OthrAttrInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'OwnershipTpCd', '所有制类型', '', 'N', 'OwnType')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'DevelopEmpNo', '开拓人(员工编号)', '', 'N', 'PioneerNo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'RelatedPerson', '客户关联人信息(对象)', 'RelatedPerson', '', 'RelClntInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'RelatedOrg', '客户关联企业信息(对象)', 'RelatedOrg', '', 'RelCorpInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'InfoIntegFlag', '信息完整性标识', '', 'N', 'Remark1')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'RgstZoneTpCd', '注册地区', '', 'N', 'RgstAreaCode')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'RegisterCapital', '注册资金信息(对象)', 'RegisterCapital', '', 'RgstCptlInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'RgstCountryTpCd', '注册国家', '', 'N', 'RgstCtyCode')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'RegisterDt', '注册登记日期', '', 'N', 'RgstDate')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'RiskLevel', '客户风险信息(对象)', 'RiskLevel', '', 'RiskLevelInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'ClientRel', '客户关系信息(对象)', 'ClientRel', '', 'RltnpInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'PremCountryTpCd', '常驻国家', '', 'N', 'RsdntCtyCode')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'ResidentTpCd', '居民类型', '', 'N', 'RsdntType')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpClntInfo', 'SpecialList', '客户特殊名单信息(对象)', 'SpecialList', '', 'SpclListInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'AdminZoneTpCd', '行政区划代码', '', 'N', 'AdmnAreaCode')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'Address', '地址信息(对象)', 'Address', '', 'AdrInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'BasicAcctBank', '基本账户行', '', 'N', 'BscAcctBrName')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'BusinessScope', '经营范围', '', 'N', 'BussScope')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'BusinessStTpCd', '经营状态', '', 'N', 'BussStatus')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'CheckInd', '复核标识', '', 'N', 'CheckFlag')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'ClientFlag', '客户标识', '', 'N', 'ClientFlag')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'ClientName', '客户名称', '', 'Y', 'ClientName')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'ClientStTpCd', '客户状态', '', 'N', 'ClientStatus')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'ClientCode', '客户类型', '', 'N', 'ClientType')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'LangTpCd', '通讯语言', '', 'N', 'CmmLangCode')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'OrgFormTpCd', '组织形式', '', 'N', 'CoFormType')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'MiitScaleTpCd', '企业规模(工信)', '', 'N', 'CompanyScale')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'OrgTpCd', '企业类型', '', 'N', 'CompanyType')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'OrgName', '企业客户名称信息(对象)', 'OrgName', '', 'CorpNameInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'CreateInst', '建立机构', '', 'N', 'CreateBranchId1')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'EstablishedDt', '成立日期', '', 'N', 'CreateDate')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'CreateTlr', '建立柜员', '', 'N', 'CreateTellerNo1')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'CreateTms', '建立时间戳', '', 'N', 'CreateTimep1')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'CtbTpCd', '贡献度类型', '', 'N', 'CtbType')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'ContactMethod', '联系方式信息(对象)', 'ContactMethod', '', 'CtcModeInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'Identifier', '证件信息(对象)', 'Identifier', '', 'CtfInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'EconomicRegionTpCd', '所属经济区域', '', 'N', 'EcmAreaCode')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'EconomicTpCd', '经济类型', '', 'N', 'EconomicChar')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'ClientId', '客户内部序号', '', 'N', 'ECIFClientNo1')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'StaffNum', '员工人数', '', 'N', 'EmpNum')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'FiInd', '金融机构标识', '', 'N', 'FIFlag')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'HistoryName', '历史名称', '', 'N', 'HistoryName')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'IndustryTpCd', '行业类型', '', 'N', 'IndustryType')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'ClientLevel', '客户等级信息(对象)', 'ClientLevel', '', 'LevelInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'ListedTpCd', '上市类型', '', 'N', 'ListedType')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'LoanCardNo', '贷款卡号', '', 'N', 'LoanCardNo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'LoanValidInd', '贷款卡有效标识', '', 'N', 'LoanValidFlag')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'LoyalScore', '忠诚度得分', '', 'N', 'LoyalScore')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'Manager', '客户管理人员信息(对象)', 'Manager', '', 'MgrInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'OffshoreInd', '离岸客户标识', '', 'N', 'OffshrFlag')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'OwnershipTpCd', '所有制类型', '', 'N', 'OwnType')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'DevelopEmpNo', '开拓人(员工编号)', '', 'N', 'PioneerNo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'RegionTpCd', '所属地区', '', 'N', 'RegionType')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'RelatedPerson', '客户关联人信息(对象)', 'RelatedPerson', '', 'RelClntInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'RelatedOrg', '客户关联企业信息(对象)', 'RelatedOrg', '', 'RelCorpInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'InfoIntegFlag', '信息完整性标识', '', 'N', 'Remark1')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'RgstZoneTpCd', '注册地区', '', 'N', 'RgstAreaCode')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'RegisterCapital', '注册资金信息(对象)', 'RegisterCapital', '', 'RgstCptlInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'RgstCountryTpCd', '注册国家', '', 'N', 'RgstCtyCode')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'RegisterDt', '注册登记日期', '', 'N', 'RgstDate')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'RiskLevel', '客户风险信息(对象)', 'RiskLevel', '', 'RiskLevelInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'PremCountryTpCd', '常驻国家', '', 'N', 'RsdntCtyCode')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'ResidentTpCd', '居民类型', '', 'N', 'RsdntType')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'SafeCode', '企业外管代码', '', 'N', 'SAFECode')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'SpclEconomicTpCd', '特殊经济区代码', '', 'N', 'SpclAreaCode')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'SpdbScaleTpCd', '企业规模(行内)', '', 'N', 'SpdbCoScale')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'SpvisorDepartment', '上级主管部门', '', 'N', 'SpvisorDeptName')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpExtendInfo', 'DefaultPb', '违约概率', '', 'N', 'UnwindPrbl')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpNameInfo', 'ActiveInd', '活动标识', '', 'N', 'ActiveFlag')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpNameInfo', 'OrgNameId', '企业客户名称内部序号', '', 'N', 'ClientNameNo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpNameInfo', 'ClientId', '客户内部序号', '', 'N', 'ECIFClientNo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpNameInfo', 'Name', '名称', '', 'Y', 'Name')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('CorpNameInfo', 'NameUsageTpCd', '名称类型', '', 'Y', 'NameType')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('EcifHeader', 'QueryHeader', '查询报文头', 'QueryHeader', 'N', 'QueryHeader')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('EcifHeader', 'requesterName', '服务请求所属用户名', '', 'N', 'RqsName')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('EcifHeader', 'requesterRole', '服务请求所属用户组', '', 'N', 'RqsRole')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('FrontFuncInfo', 'ChildFrontFunc', '子功能点', 'ChildFrontFunc', '', 'ChildFrontFunc')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('FrontFuncInfo', 'ExtendDest', '扩展目标', '', '', 'ExnTarget')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('FrontFuncInfo', 'FuncId', '前端功能点ID', '', '', 'FuncId1')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('FrontFuncInfo', 'FuncName', '前端功能点名称', '', '', 'FuncName')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('FrontFuncInfo', 'FuncDest', '前端功能点目标', '', '', 'FuncTarget')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('FrontFuncInfo', 'RoleId', '所属角色ID', '', '', 'RoleId1')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('FrontFuncInfo', 'FFuncRoleExtendDest', '角色关系的目标', '', '', 'RoleRelTrgt')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('FrontFuncInfo', 'Status', '状态', '', '', 'Status')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('GrpInfo', 'ChildGroupList', '子用户组信息列表', 'ChildGroupList', '', 'ChildGrpList')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('GrpInfo', 'ChildOrgs', '子机构列表', 'ChildOrgs', '', 'ChildInsts')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('GrpInfo', 'FrontFuncInfoList', '前端功能列表', 'FrontFuncInfoList', '', 'FrontFuncInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('GrpInfo', 'GroupId', '用户组ID', '', '', 'GroupId')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('GrpInfo', 'GroupName', '用户组名称', '', '', 'GroupName')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('GrpInfo', 'HLevel', '用户组HLevel', '', '', 'HLevel')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('GrpInfo', 'Description', '用户组描述', '', '', 'Remark')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('GrpInfo', 'RoleInfoList', '角色信息列表', 'RoleInfoList', '', 'RoleInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('GrpInfo', 'TaskInfoList', '任务信息列表', 'TaskInfoList', '', 'TaskInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('GrpInfo', 'UserExtendedInfoXml', '用户自定义属性', '', '', 'UserExnAttr')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('InstInfo', 'BranchId', '分行代码', '', '', 'BranchId')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('InstInfo', 'ChildGroupList', '子用户组信息列表', 'ChildGroupList', '', 'ChildGrpList')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('InstInfo', 'ChildOrgs', '子机构列表', 'ChildOrgs', '', 'ChildInsts')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('InstInfo', 'CountryCode', '国家代码', '', '', 'CountryCode')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('InstInfo', 'FrontFuncInfoList', '前端功能列表', 'FrontFuncInfoList', '', 'FrontFuncInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('InstInfo', 'HLevel', '机构的HLevel', '', '', 'HLevel')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('InstInfo', 'OrgExtendedInfoXml', '机构自定义属性', '', '', 'InstExnAttr')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('InstInfo', 'OrgId', '机构ID', '', '', 'InstId1')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('InstInfo', 'OrgName', '机构名称', '', '', 'InstName')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('InstInfo', 'OrgType', '机构类型', '', '', 'InstType')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('InstInfo', 'Description', '注释', '', '', 'Remark')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('InstInfo', 'RoleInfoList', '角色信息列表', 'RoleInfoList', '', 'RoleInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('InstInfo', 'TaskInfoList', '任务信息列表', 'TaskInfoList', '', 'TaskInfo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('InstInfo', 'TreeType', '所属机构树类型', '', '', 'TreeType')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('InstInfo', 'UserExtendedInfoXml', '用户自定义属性', '', '', 'UserExnAttr')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('OrgCpcInfo', 'ZoneId', '地区ID', '', '', 'AreaCode')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('OrgCpcInfo', 'IsDelegatee', '是否可以被其他机构代理', '', '', 'AvlBeDelegatedFlag')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('OrgCpcInfo', 'IsDelegate', '是否可以代理其他机构的业务', '', '', 'AvlDelegateFlag')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('OrgCpcInfo', 'OrgBizProperty', '业务机构属性', '', '', 'BsnInstAttr')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('OrgCpcInfo', 'OrgCategory', '业务机构类别', '', '', 'BsnInstCgy')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('OrgCpcInfo', 'OrgBizType', '业务机构类型', '', '', 'BsnInstType')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('OrgCpcInfo', 'CityExNo', '同城交换号', '', '', 'CityExgInstId')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('OrgCpcInfo', 'PresentPayNo', '现代支付号', '', '', 'CNAPSBnkNo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('OrgCpcInfo', 'OCRIP', '影像系统IP地址', '', '', 'ImageStmIPAdr')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('OrgCpcInfo', 'Address', '机构地址', '', '', 'InstAdr')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('OrgCpcInfo', 'OrgId', '业务机构ID', '', '', 'InstId1')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('OrgCpcInfo', 'ProveIP', '验印系统IP地址', '', '', 'YYXTStmIPAdr')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('QueryHeader', 'availableResultsCount', '该页记录数', '', '', 'AvlRsltNum')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('QueryHeader', 'pageEndIndex', '分页结束位置', '', '', 'EndIdnx')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('QueryHeader', 'returnAvailableResultCount', '该页存在记录数', '', '', 'RetAvlRsltNum')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('QueryHeader', 'pageStartIndex', '分页起始位置', '', '', 'StartIdnx')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('RltnpInfo', 'ToClientId', '从属关系客户号', '', 'Y', 'AsgnClientNo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('RltnpInfo', 'EndTms', '结束时间戳', '', 'N', 'EndTimep')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('RltnpInfo', 'FromClientId', '主体关系客户号', '', 'Y', 'MainClientNo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('RltnpInfo', 'ClientRelId', '客户关系信息内部序号', '', 'N', 'RelInfoNo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('RltnpInfo', 'Description', '客户关系描述', '', 'N', 'Remark')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('RltnpInfo', 'RelTpCd', '关系类型', '', 'Y', 'RltnpType')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('RltnpInfo', 'StartTms', '开始时间戳', '', 'N', 'StartTimep')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('RoleInfo', 'AppId', '所属应用程序Id', '', '', 'AppId')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('RoleInfo', 'Description', '注释', '', '', 'Remark')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('RoleInfo', 'RoleId', '角色ID', '', '', 'RoleId1')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('RoleInfo', 'RoleName', '角色名称', '', '', 'RoleName')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('RoleInfo', 'IsSystemUsed', '是否被系统使用', 'True
False', '', 'SysUsedFlag')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('TaskInfo', 'ChildTasks', '子任务列表', 'ChildTasks', '', 'ChildTasks')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('TaskInfo', 'TaskDestination', '任务代码', '', '', 'TaskCode')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('TaskInfo', 'TaskId', '任务ID', '', '', 'TaskId1')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('TaskInfo', 'TaskName', '任务名称', '', '', 'TaskName')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('UserAdvInfo', 'OfficeFax', '公司传真', '', '', 'CompanyFaxNo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('UserAdvInfo', 'OfficeTel', '公司电话', '', '', 'CompanyTel')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('UserAdvInfo', 'Email', '电子邮件', '', '', 'Email')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('UserAdvInfo', 'EmpolyeeNumber', '用户员工号  ', '', '', 'EmployeeNo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('UserAdvInfo', 'JobTitle', '用户职位    ', '', '', 'JobTitle')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('UserAdvInfo', 'LanguageId', '语言代码', '', '', 'LangCode1')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('UserAdvInfo', 'HandPhone', '手机', '', '', 'Mobile')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('UserAdvInfo', 'Pager', '传呼机号码', '', '', 'PagerNo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('UserAdvInfo', 'Description', '注释', '', '', 'Remark')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('UserAdvInfo', 'Counter', '柜员号', '', '', 'TellerNo')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('UserBscInfo', 'UserId', '用户ID', '', '', 'UserId')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('UserBscInfo', 'UserName', '用户姓名', '', '', 'UserName')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('UserCpcInfo', 'CoreCashLimit', '核心现金限额', '', '', 'CoreCashLmt')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('UserCpcInfo', 'CoreRoleId', '核心角色ID', '', '', 'CoreRlId')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('UserCpcInfo', 'CoreTranLimit', '核心转账限额', '', '', 'CoreTranLmt')
;
INSERT INTO  METADATA_STRUCTS_ATTR(STRUCTID, ELEMENTID, ELEMENTNAME, REMARK, ISREQUIRED, METADATAID)
  VALUES('UserCpcInfo', 'IsCoreUser', '是否核心角色', '', '', 'CoreUserFlag')
;
COMMIT;
COMMIT;
