DROP TABLE  AUDITSTATE;
CREATE TABLE  AUDITSTATE  ( 
	ID   	VARCHAR(25) NOT NULL,
	STATE	VARCHAR(40) NOT NULL 
	)
;
COMMENT ON TABLE  AUDITSTATE IS '审核状态表'
;
COMMENT ON COLUMN  AUDITSTATE.ID IS 'ID主键'
;
COMMENT ON COLUMN  AUDITSTATE.STATE IS '审核状态'
;
INSERT INTO  AUDITSTATE(ID, STATE)
  VALUES('0', '新增')
;
INSERT INTO  AUDITSTATE(ID, STATE)
  VALUES('1', '待审核')
;
INSERT INTO  AUDITSTATE(ID, STATE)
  VALUES('2', '通过')
;
INSERT INTO  AUDITSTATE(ID, STATE)
  VALUES('3', '拒绝')
;
COMMIT;
COMMIT;
