DROP TABLE  DEFAULT_INTERFACE;
CREATE TABLE  DEFAULT_INTERFACE  ( 
	INTERFACEID  	VARCHAR(40) NOT NULL,
	INTERFACENAME	VARCHAR(200),
	INTERFACETYPE	VARCHAR(50),
	SERVICEID    	VARCHAR(40) 
	)
;
COMMENT ON TABLE  DEFAULT_INTERFACE IS '默认接口信息表'
;
COMMENT ON COLUMN  DEFAULT_INTERFACE.INTERFACEID IS '接口ID'
;
COMMENT ON COLUMN  DEFAULT_INTERFACE.INTERFACENAME IS '接口名称'
;
COMMENT ON COLUMN  DEFAULT_INTERFACE.INTERFACETYPE IS '接口方向(1:提供方 2:调用方)'
;
COMMENT ON COLUMN  DEFAULT_INTERFACE.SERVICEID IS '服务ID'
;
INSERT INTO  DEFAULT_INTERFACE(INTERFACEID, INTERFACENAME, INTERFACETYPE, SERVICEID)
  VALUES('default_interface_consumer', '默认标准接口', '0', 'SHEAD')
;
INSERT INTO  DEFAULT_INTERFACE(INTERFACEID, INTERFACENAME, INTERFACETYPE, SERVICEID)
  VALUES('default_interface_provider', '默认标准接口', '1', 'SHEAD')
;
INSERT INTO  DEFAULT_INTERFACE(INTERFACEID, INTERFACENAME, INTERFACETYPE, SERVICEID)
  VALUES('default_interface_consumer1', '默认标准接口', '0', 'SHEAD1')
;
INSERT INTO  DEFAULT_INTERFACE(INTERFACEID, INTERFACENAME, INTERFACETYPE, SERVICEID)
  VALUES('default_interface_provider1', '默认标准接口', '1', 'SHEAD1')
;
INSERT INTO  DEFAULT_INTERFACE(INTERFACEID, INTERFACENAME, INTERFACETYPE, SERVICEID)
  VALUES('OutSOPTemplate', 'Out端SOP模板接口', '0', 'SOPAbstractService')
;
INSERT INTO  DEFAULT_INTERFACE(INTERFACEID, INTERFACENAME, INTERFACETYPE, SERVICEID)
  VALUES('InSOPTemplate', 'SOP模板接口', '0', 'SOPAbstractService')
;
COMMIT;
COMMIT;
