DROP TABLE  IDA_BAK;
CREATE TABLE  IDA_BAK  ( 
	ID          	VARCHAR(40) NOT NULL,
	STRUCTNAME  	VARCHAR(100),
	STRUCTALIAS 	VARCHAR(100),
	METADATA_ID 	VARCHAR(40),
	SEQ         	INTEGER,
	TYPE        	VARCHAR(10),
	SCALE       	VARCHAR(5),
	LENGTH      	VARCHAR(10),
	REQUIRED    	VARCHAR(10),
	PARENT_ID   	VARCHAR(40),
	INTERFACE_ID	VARCHAR(100) 
	)
;
COMMENT ON TABLE  IDA_BAK IS 'IDA备份表'
;
COMMIT;
COMMIT;
