DROP TABLE  OPERATION_HISTORY;
CREATE TABLE  OPERATION_HISTORY  ( 
	OPERATION_ID     	VARCHAR(255) NOT NULL,
	SERVICE_ID       	VARCHAR(40) NOT NULL,
	OPERATION_NAME   	VARCHAR(100),
	REMARK           	VARCHAR(500),
	OPERATION_VERSION	VARCHAR(25) NOT NULL,
	OPERATION_STATE  	VARCHAR(25) NOT NULL,
	SERVICE_VERSION  	VARCHAR(25) NOT NULL,
	MODIFYUSER       	VARCHAR(50),
	UPDATETIME       	VARCHAR(50) 
	)
;
COMMENT ON TABLE  OPERATION_HISTORY IS '操作历史信息表'
;
COMMENT ON COLUMN  OPERATION_HISTORY.OPERATION_ID IS '操作ID'
;
COMMIT;
COMMIT;
