DROP TABLE  SDA_HISTORY;
CREATE TABLE  SDA_HISTORY  ( 
	ID               	VARCHAR(100) NOT NULL,
	STRUCT_ID        	VARCHAR(100) NOT NULL,
	METADATA_ID      	VARCHAR(100) NOT NULL,
	TYPE             	VARCHAR(10),
	SEQ              	INTEGER,
	REQUIRED         	VARCHAR(10),
	REMARK           	VARCHAR(3000),
	OPERATION_ID     	VARCHAR(255) NOT NULL,
	OPERATION_VERSION	VARCHAR(50) NOT NULL,
	SERVICE_ID       	VARCHAR(40) NOT NULL,
	SERVICE_VERSION  	VARCHAR(50) NOT NULL,
	PARENT_ID        	VARCHAR(40),
	MODIFYUSER       	VARCHAR(50),
	UPDATETIME       	VARCHAR(50) 
	)
;
COMMENT ON TABLE  SDA_HISTORY IS '服务SDA历史表'
;
COMMIT;
COMMIT;
