DROP TABLE  SG_ORG;
CREATE TABLE  SG_ORG  ( 
	ORG_ID    	VARCHAR(255) NOT NULL,
	ORG_NAME  	VARCHAR(255) NOT NULL,
	ORG_AB    	VARCHAR(255) NOT NULL,
	ORG_STATUS	VARCHAR(255) NOT NULL 
	)
;
COMMENT ON TABLE  SG_ORG IS '机构基本信息表'
;
COMMENT ON COLUMN  SG_ORG.ORG_ID IS '结构ID'
;
COMMENT ON COLUMN  SG_ORG.ORG_NAME IS '机构中文名称'
;
COMMENT ON COLUMN  SG_ORG.ORG_AB IS '机构简称'
;
COMMENT ON COLUMN  SG_ORG.ORG_STATUS IS '状态'
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('000000', '总行名称', '总行', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0001', '核心业务系统', 'SOP', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0204', '代客及代理业务处理平台', 'MMPP', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0003', '总行大前置系统', 'ZHIPP', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0004', '分行大前置系统', 'FHIPP', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0005', '核心前台系统', 'COP', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0006', '业务集中CPC/SDP系统', 'CPC', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0007', '已删除系统', 'NOCP', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0008', '统一认证授权平台', 'UAAS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0009', '工作流平台业务集中系统', 'BPMP', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0010', '工作流平台综合业务系统', 'GZL', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0012', '影像平台综合业务系统', 'Image', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0013', 'OCR系统', 'OCR', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0014', '个人网银系统', 'nbper', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0015', '公司网银系统', 'nbent', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0016', '信用卡网银系统', 'icard', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0017', '个人手机银行系统', 'mbper', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0018', '公司手机银行系统', 'mbent', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0019', '电子商务支付平台', 'epay', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0020', '通知平台系统', 'mdp', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0021', '客服话务接入系统', 'PBX', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0022', '客服话务处理系统', 'CTI', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0023', '客服电话银行系统', 'IVR', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0024', '客服座席综合应用系统', 'CSR', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0025', '客服业务处理系统', 'BPP', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0026', '黄金交易管理系统', 'HJJY', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0027', '理财业务销售系统', 'PWM', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0028', '外汇宝系统', 'WHB', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0029', '银基通系统', 'YJT', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0030', '第三方存管系统', 'SFCG', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0031', '第三方存管深证通系统', 'SZT', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0032', '单证系统', 'EE', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0033', '离岸核心系统', 'OSA', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0034', '现代支付系统', 'CNAPS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0035', 'SWIFT系统', 'SWIFT', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0036', '信用卡发卡系统', 'CC', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0037', '信用卡前置系统', 'BCMS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0038', '信用卡密钥管理系统', 'SECU', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0039', '信用卡POSP系统', 'POSP', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0040', '外部网站系统', 'WBWZ', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0041', '业务域基础平台', 'YWYJC', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0043', '网上支付跨行清算系统', 'IBPS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0044', '新一代网点平台系统', 'FES', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0045', '移动通讯前置系统', 'TXQZ', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0046', '金融IC卡业务系统', 'ICS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0047', '集中式收单系统', 'CCAS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0048', '工作流平台网点应用系统', 'BPMP', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0053', '灾备SAN网系统', 'ZBSAN', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0054', '灾备集中存储系统', 'ZBCC', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0200', '企业服务总线', 'ESB', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0201', '企业级客户信息管理系统', 'ECIF', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0202', '业务集成平台', 'BIP', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0301', '业务集中外包系统', 'WB', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0302', '工作流平台信用卡应用系统', 'BPMP', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0304', '联网核查公民身份信息系统', 'idc', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0305', '网银证书及安全系统', 'RACA', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0306', '客服辅助系统', 'CFZ', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0307', '收单系统', 'POS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0308', 'HDQ历史数据查询系统', 'HDQ', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0309', '代发代扣系统', 'df', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0310', '个贷系统', 'gd', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0311', '综合积分管理系统', 'JIF', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0312', '个贷资产保全系统', 'zcbq', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0313', '储蓄国债系统', 'BOND', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0314', '理财业务管理系统', 'TA', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0315', '卡外围系统', 'KWW', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0316', '缴费及支付系统', 'DSF', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0317', '企业年金帐管系统', 'SPMS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0318', '电子商务交易资金托管系统', 'dzsw', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0319', '小额定期借记业务系统', 'XEZF', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0320', '信用证系统', 'XYZ', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0321', '银保通系统', 'YBT', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0322', '网上贸易服务系统', 'WSMF', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0323', '离岸反洗钱监测报告系统', 'AMLOF', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0324', '集中核押系统', 'HYXT', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0325', '验印系统', 'YYXT', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0326', '集中验印系统', 'JZYY', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0327', '现金管理系统', 'CMP', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0328', '银企直联系统', 'YQZL', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0329', '保理系统', 'BLXT', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0330', '银关通系统', 'ygt', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0331', '支付密码系统', 'SZM', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0332', '商业汇票系统', 'SYHP', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0333', '全国支票影像交换系统', 'CIS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0334', '国库信息处理系统', 'TIPS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0335', '境内外币支付系统', 'JNWB', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0336', '外汇金宏系统', '外汇金宏系', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0337', '结售汇及报价平盘系统', 'XFUND', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0338', '资金集中计价系统', 'FTP', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0339', 'SAP-TR系统', 'SAPTR', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0340', 'TR-SWIFT系统', 'TRSW', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0341', '市场风险限额管理系统', 'MLS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0342', '信用卡VISA接口机', 'VAP', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0343', '信用卡MASTERCARD接口机', 'MIP', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0344', '信用卡JCB接口机', 'JIPS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0345', '信用卡欺诈侦测系统', 'PRM', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0346', '信用卡综合审批系统', 'EAPS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0347', '信用卡申请欺诈侦测系统', 'INSTI', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0348', '信用卡催收系统', 'CS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0349', '信用卡报表系统', 'WRPT', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0350', '信用卡个人征信系统', 'ICR', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0351', '信用卡数据处理系统', 'DPS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0352', '信用卡通知平台前置系统', 'SMSP', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0353', '信用卡文件传输系统', 'FTC', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0354', '信用卡协同应用系统', 'MTS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0355', '信用卡反洗钱监测报告系统', 'CAML', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0356', '现金流分析管理系统', 'XJLFX', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0357', '综合帐单系统', 'ZHZD', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0358', '数据仓库系统', 'EDW', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0359', '汇聚平台', 'HJPT', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0360', '采集主机系统', 'cj', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0361', 'HPS报表系统', 'HPS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0362', 'SAP人力系统', 'saphr', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0363', 'SAP财务系统', 'SAPGL', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0364', 'TOTAL系统', 'TOL', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0365', '高管信息服务系统', 'GGXX', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0366', '风险管理信息系统', 'ALS6', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0367', '对公内部评级系统', 'IRS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0368', '运营内控系统', 'OICS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0369', '公司及投资银行客户关系管理系统', 'CCRM', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0370', '个人银行客户关系管理系统', 'PCRM', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0371', '总行反洗钱监测报告系统', 'AML', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0372', '银监会客户风险报送系统', 'CRS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0373', '1104监管报送系统', '1104', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0374', '征信系统', 'ICR', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0375', '资金预算和头寸管理系统', 'ZJTC', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0376', '全行ATM终端', 'ATM', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0377', '公文管理系统', 'OA', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0378', '金融制裁名单监测系统', 'JRZC', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0379', '财富管理系统', 'WMS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0380', '服务整合平台', 'SIP', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0381', '制卡系统', 'zkxt', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0382', '黄金清算行系统', 'HJQS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0383', '村镇银行系统', 'czyh', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0384', '村镇支付密码系统', 'CZMM', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0385', '电视银行系统', 'DSYH', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0386', '流动性风险管理信息系统', 'LRM', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0387', '额度管理系统', 'CLM', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0388', '报表与信息服务平台系统', 'BI', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0389', '银证通行情服务系统', 'YZTHQ', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0390', '理财估值核算系统', 'LCGZ', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0391', '海关税费电子支付系统', 'CEPS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0392', '实物资产管理信息系统', 'SWZC', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0393', '第三方存管监管报送系统', 'CGBS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0394', '金融IC卡密钥管理系统', 'ICMG', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0395', '零售评分卡决策系统', 'RDS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0396', '金融IC卡数据准备系统', 'ICDM', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0397', '市场风险内部模型系统', 'IMA', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0398', '风险加权资产系统', 'RWA', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0399', '代理西联汇款系统', 'WU', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0400', '外汇报价引擎系统', 'XPRIC', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0401', '路透电子交易系统', 'RETAD', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0402', 'KONDOR系统', 'KON', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0403', '路透市场数据服务系统', 'RMDS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('default', '默认机构', 'default', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0404', '移动办公应用平台', 'ydbg', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0405', '银行账户利率风险管理系统', 'IRRBB', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0406', '人事代发系统', 'rsdf', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0407', '人事福利系统', 'rsfl', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0408', 'SAP-PA系统', 'SAPPA', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0409', '证交所债券交易系统', 'ZZQ', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0410', '积分商城系统', 'pmall', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0411', '银联清算文件接收系统', 'CFS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0412', '企业年金和保险资产托管系统', 'NJTG', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0413', '投资风险管理与绩效评估系统', 'FXJX', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0414', '资产托管业务综合系统', 'ZCTG', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0415', '办公域基础平台', 'BGY', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0416', '邮件系统', 'MAIL', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0421', '供应链金融电子平台系统', 'SCF', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0422', 'COMSTARIMIX前置系统', 'CSTAR', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0423', '利率定价管理系统', 'FTPP', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0299', '中移动手机汇款系统', 'cmpay', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0138', '人行信用报告查询系统', 'BQS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0426', '村镇银行反洗钱监测报告系统', 'CZAML', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0428', '柜员指纹系统', 'GYZW', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0432', '信用卡美国运通接口机', 'AE', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0701', '柜面终端管控系统', 'ZDGK', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0702', '业务集中报表系统', 'NRPT', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0703', '综合信息服务系统', 'zhxx', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0704', '自助设备监控系统', 'ZZJK', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0705', '股指期货特别结算系统', 'QHTJ', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0706', '离岸传真系统', 'FAXOF', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0707', '人民币跨境收付信息管理系统', 'RCFE', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0708', '信用卡案件管理系统', 'CMS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0709', '信用卡帐单查询系统', 'Cmod', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0710', '信用卡制卡文件传输系统', 'CFT', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0711', '信用卡照片卡系统', 'PCARD', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0712', '信用卡会计准则转换系统', 'ARCS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0713', '信用卡交易监控系统', 'CMON', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0715', '审计管理信息系统', 'AWP', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0716', '银税信息共享系统', 'BTIS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0717', '资财系统', 'zicai', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0173', '自助报销系统', 'EA', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0719', '年终考核管理系统', 'nzkh', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0720', '自助数据综合分析应用系统', 'LSFX', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0721', '印章信息管理系统', 'yzg', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0722', '股权投资信息系统', 'PE', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0723', '村镇银行报表与信息服务系统', 'CZXI', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0725', '通联支付系统', 'tlzf', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0726', '理财与资金信托数据报送系统', 'CAFCS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0727', '人事外围系统', 'rsww', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0728', '人事招聘系统', 'rszp', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0729', 'SAP-Solman系统', 'slm', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0730', 'SAP-BW系统', 'SAPBW', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0731', 'SAP-Router系统', 'SAPRT', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0732', 'SAP-SNC系统', 'SNC', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0733', 'Butterfly系统', 'BF', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0734', 'Firefly系统', 'FF', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0752', '内部网站系统', '内部网站', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0753', '培训中心考试学习系统', 'pxxt', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0754', 'Internet代理服务系统', 'DLFW', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0755', '办公Mcafee邮件网关过滤系统', 'YJWG', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0756', '邮件营销系统', 'YJYX', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0757', '总行传真系统', 'ZHCZ', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0758', '深信服上网管理系统', 'SXF', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0759', '一卡通系统', 'YKT', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0760', '电子文件柜系统', '电子文件柜', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0761', '跨网段ISA发布系统', 'ISA', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0763', '办公SMS软件信息管理系统', 'BGSMS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0764', 'SIP即时消息服务系统', 'lync', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0765', '数字证书服务系统', 'CAZS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0766', '全行vpn安全接入系统', 'VPN', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0771', 'AD用户管理系统', 'ADYH', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0773', 'vpn拨入系统', 'VPN', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0774', '总行用户文件备份系统', 'YHBF', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0776', 'RMS信息权限管理系统', 'RMS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0778', 'ATM软件信息监测平台系统', 'ATMJK', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0782', 'IT服务台系统', 'ITSM', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0783', '集中监控平台系统', 'xtjk', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0791', '贸易服务台系统', 'MYFW', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0792', '核心系统交易分析和监控系统', 'hxjk', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0802', '元数据管理系统', 'DS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0803', '数据质量管理系统', 'DQ', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0806', '风险量化策略平台系统', 'RQS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0809', '培训管理系统', 'pxgl', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0810', '企业级内网门户系统', '内网门户', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0815', '实物金登记系统', 'HLC', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0825', '柜面及消息服务系统', 'NBH', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0205', '业务流程管理平台', 'BPMP', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0203', '会计核算及总账系统', 'GLS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0209', '统一身份和访问管理系统', 'UIAS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0437', '移动营销平台', 'MMP', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0211', '报表及数据分析平台', 'NRPT', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0213', '金融市场交易管理平台', 'GMP', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0217', '机构管理系统', 'OIMS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0300', '非现金自助渠道服务系统', 'FXZZ', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0076', '微信银行系统', 'WCBS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0084', '在线客服系统', 'ESVC', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0110', '对公债项评级系统', 'FRS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0059', '影像内容管理服务平台', 'YXNR', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0212', '抵质押品管理系统', 'CMIS', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0094', '网上金融超市', 'FMALL', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0106', '互联网金融信息交换平台', 'NBIA', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0112', '客服终端安全管控系统', 'KFGK', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0149', '电子银行交易监控系统', 'EBTM', '1')
;
INSERT INTO  SG_ORG(ORG_ID, ORG_NAME, ORG_AB, ORG_STATUS)
  VALUES('0215', '零售信贷服务系统', 'PLBS', '1')
;
COMMIT;
COMMIT;
