DROP TABLE  SG_ROLE;
CREATE TABLE  SG_ROLE  ( 
	ROLE_ID    	INTEGER NOT NULL,
	ROLE_NAME  	VARCHAR(255) NOT NULL,
	ROLE_REMARK	VARCHAR(255) 
	)
;
COMMENT ON TABLE  SG_ROLE IS '角色基本信息表'
;
COMMENT ON COLUMN  SG_ROLE.ROLE_ID IS '角色ID'
;
COMMENT ON COLUMN  SG_ROLE.ROLE_NAME IS '角色名称'
;
COMMENT ON COLUMN  SG_ROLE.ROLE_REMARK IS '描述'
;
INSERT INTO  SG_ROLE(ROLE_ID, ROLE_NAME, ROLE_REMARK)
  VALUES(1, '管理员', '管理员')
;
INSERT INTO  SG_ROLE(ROLE_ID, ROLE_NAME, ROLE_REMARK)
  VALUES(2, '服务审核人员', '服务审核人员')
;
INSERT INTO  SG_ROLE(ROLE_ID, ROLE_NAME, ROLE_REMARK)
  VALUES(3, '服务定义人员', '进行业务分析、服务的定义与发布')
;
INSERT INTO  SG_ROLE(ROLE_ID, ROLE_NAME, ROLE_REMARK)
  VALUES(4, '配置开发人员', '对已发布的服务进行开发配置')
;
INSERT INTO  SG_ROLE(ROLE_ID, ROLE_NAME, ROLE_REMARK)
  VALUES(5, '接入系统开发人员', '接入系统开发人员')
;
INSERT INTO  SG_ROLE(ROLE_ID, ROLE_NAME, ROLE_REMARK)
  VALUES(6, '访客', '访客')
;
COMMIT;
COMMIT;
